### ISSUE TITLE
Trakt lists slow loading

### ISSUE THREAD

**Issue by Axxel6307** [123Venom/plugin.video.venom#11] opened 2019-07-18 03:48 UTC
I see under your news and info that you are working on slow loading menus. Is trakt part of this? 

My trakt lists in venom take about 45 seconds to load as opposed to under 10 seconds in other Exodus forks. 

Can send you a log if you'd like. 

Thanks for your work!

**Comment by 123Venom** [comment] 2019-07-18 07:53
It is an area I want to go over and see but a few things to note, especially if it's the Trakt Progress list your seeing as being real slow.  First I got a few complaints about episodes not updating in the list right after they watch them.  Well the obvious is that the lists are cached for a small duration of 15min, and they loaded for me in 4secs on my shield cached, Gaia caches for 12min.  So I removed the cache to combat those complaint but users did not realize the consequence of the change they were requesting.  Removing a cache function is going to SLOW it down, but they got their request, now they complaint the other way and I said ya can't have it both ways.  Now 45secs is disgusting and abnormal to me.  On my windows setup it loads in 12secs, with no cached data and each subsequent entry was 5 seconds because there is still some caching going on that kodi handles, like thumbnails.  On my Shield the load time is 14secs and subsequent about 8.  Yes I timed it because of the complaints.  Is this a firestick?  Seems to be the common problem with slow load times but 45 secs is the largest I've heard thus far.  I seriously do not think I could cut that down to 12-14 seconds without removing all the code work I've done.  I added some options to help, like "Page Item Limit" and "Disable Extended artwork".  I could talk for some time about all the artwork changes I did and I know that increased load times but was a change sooner or later would be forced on us devs.  fanart.tv is slowly moving away from 1080res fanart, landscape artwork, even poster artwork is increasing in res.  Some exo forks are missing artwork and this is why and it will worsen over time till they make the change.  Sadly for slowler devices it's just going to keep getting slower as more and more code is added.  I'll look into it but honestly you'd be about number 12 on this request list right now and I don't dare comment when that may mean I can possibly get to looking at this. This is one big reason I tell people Window, Shield, nor nothing.

**Comment by axxell6307** [comment] 2019-07-18 11:17
Yeah these are on shields. The fire sticks take longer lol. I've tried with different page limits and disabled artwork.

**Comment by ricklepick** [comment] 2019-07-18 11:38
I use KODI 17.6 on RPi3 with the recommended "Page Item Limit" value and "Disable Extended artwork" on. Since the cache change my Trakt times have gone from around 8 secs to 20. Personally I'd rather those times be fast and automatic 'watched in Trakt' be broken. You could always use the context menu to mark something watched anyway. Maybe add the cache code back and make it a user option?

**Comment by 123Venom** [comment] 2019-07-18 13:21
> 
> 
> I see under your news and info that you are working on slow loading menus. Is trakt part of this?
> 
> My trakt lists in venom take about 45 seconds to load as opposed to under 10 seconds in other Exodus forks.
> 
> Can send you a log if you'd like.
> 
> Thanks for your work!

45 seconds on a Shield?  I've never seen any menu anywhere take that long...something is up and if I had a 45 sec load time I'd be the first one yelling.  I'm around 14-15 secs on a Shield with wired 300mbps plan... @ricklepick is at 20 and you're at 45 tells me time to start investigating setup and maintenance. The again you said other Exo forks around 10...what one in particular?  I'll run a comp on two different machines but I do know my added artwork code is going to make it slightly slower but not by 35 secs.

**Comment by axxell6307** [comment] 2019-07-18 13:47
To take the guess work, I just ran my stopwatch and got the following:
Trakt Custom List load time: Venom 49s, Scrubsv2 5s, Yoda 10s, Watchdog 9s.
Trakt progress load time: Venom 30s, scrubsv2 3s, Yoda 3s, watchdog 4s.

I am using google dns in my router and have tried it on both shields and also on my cell phones Tmobile connection and have similar load times.

Now that I am typing this, I realize before I hadn't noted I'm using custom trakt lists, not the standard collection or watchlist, fwiw.

**Comment by 123Venom** [comment] 2019-07-18 14:24
Is your custom list public?  

Running a quick test on windows setup for Trakt Progress I get....
all cache cleared inside addon and system wide using AfterMath
Venom 1st-14secs, 2nd-5secs
Overeasy 1st-4secs, 2nd-2secs
Redux 1st-5secs, 2nd-3secs
scrubsv2 1st-5secs, 2nd-3secs

I have no idea why your Venom load time is so disgusting.  What is load time going in a 2nd time? I know it's slower than other exo forks, for known reasons I explained.  Here's one way I can show you what I mean...go into the history in any exo fork..0 artwork! They do not gather ANY so what you end up with is the addon icon and addon fanart, that's 8yr old code that was never finished and it goes on from there with other lists in the "My Lists" menu.  I'll try and take a look and see if there is something I added that is causing the lag on initial entry.  But the last thing I'm doing is resorting back to 8yr old code from an exo fork and remove artwork that I'm trying to bring up to date.  I'll see if I can look into this over the weekend.

**Comment by axxell6307** [comment] 2019-07-18 14:45
No it's a private list. Yeah, going in a second load cuts my progress down to about 10 to 15 seconds. Didn't help the trakt list time though.

I have 229 shows on my trakt list btw if that makes a difference. 

Anyway, appreciate it and if you ever have a chance to work on it! I love seeing the popup news info after an update to see what you've done. Nice feature!

**Comment by 123Venom** [comment] 2019-07-18 15:15
Well you did peak my interest because your load times are really ugly.  I had a quick look and experimented briefly because I need to get back to work.  I was able to shrink load time by 2secs by removing an api call that UpNext requires for episodeIDS that exo forks do not gather.  Then I was able to shrink another 1.5secs off by removing episode counters..another feature exo forks do not have.  Sadly the pattern I'm seeing here, in a quick review, is to get the speed back would mean I'd have to remove all the enhanced features I've added and that I seriously doubt I'll have an interest in undoing all that work.  It needs more time to investing but in the mean time I suggest doing a fresh install of Venom because your load times do not sound normal at all, but I agree it's definitely slower than a typical exo fork but I understand why.  I'll hunt out and test anything causing undesired lag and see what I can do.  

Ya the intent with that newsinfo was to keep people informed of what I'm working on but finding the free time to maintain it has not been easy being a one man show.  I have half completed additions all over the place at the moment but feel like the last month I've turned into Mr. technical support so not much progress is being made in the right places.  Sure could use a nice team!

**Comment by axxell6307** [comment] 2019-07-18 15:20
The cell phone kodi was new install. I'll do the shield when I get a chance.

Wish I could help! No coding experience and unable to spend much time on a pc due to health issues. Don't burn yourself out man! Hopefully you can get some solid streaming time in and enjoy your work lol

**Comment by 123Venom** [comment] 2019-07-18 15:21
and Overeasy 2nd pass was crazy fast at 2secs btw so that's what I'm comparing code against and turning off added code in mine little by little to see if I can find any crazy long lag.  If it ends up being a few seconds here and there for each added feature chance are I can't do anything about it and it's the draw back of adding features and more code. Fingers crossed something turns up.

**Comment by 123Venom** [comment] 2019-07-18 15:23
cell phone?  You said it was on a shield in your 2nd response.  That's a huge reason.  That's going to be notoriously slow.  I'd stick with an older fork with less features from a cell phone for sure!

**Comment by axxell6307** [comment] 2019-07-18 15:26
Sorry for the confusion. All my posted times were on the shields. Later on, I installed on my cell phone so I could use different isp (tmobile) for comparison. The cell phone was a new install.  Shields were not but I will do one soon.

**Comment by 123Venom** [comment] 2019-07-18 15:30
ya do a fresh install on the shield because something is way off there.  Just curious but do you use UpNext in Venom?  I had a thought on how I could shave that 2secs off for people who disable UpNext and can avoid an api request if disabled....a code check for that option so to speak.

**Comment by axxell6307** [comment] 2019-07-18 15:48
Just cleared my kodi data and redid it in a shield. Same load time.

No, I haven't used or installed nextup. Should I try?

**Comment by 123Venom** [comment] 2019-07-18 16:09
NextUp is the former name.  I just wanted to know if you use the option.  I may considering adding some code that checks if this is disabled so I can avoid an api request for data that it needs.  The less api requests the faster

**Comment by 123Venom** [comment] 2019-07-18 20:17
ya know what you could do, that I just got smacked hard with, is make sure you have Venom dug enabled in settings and set to "Addon" then check the venom.log.  I was running some more test and found one nasty lag.  My season counter at the episode level is really slowing it down...like 5secs when I turned the counter off. Then all of a sudden while testing the load time shot up to 30secs, alarming and I knew something was up.  First thing I did was check the log and found trakt was down and log loaded with timeout and 502 errors, we can't do anything about when their servers take a dump like that.  I just had to walk away and wait till later it comes back more consistent.  If this counter is causing issues I'm going to remove it except at the TVShows level so you only get a TotalSeason count there when checking Info and honestly I think that's all that is needed...especially if it lags bad at other levels like I saw till trakt servers took a shit...lol

**Comment by axxell6307** [comment] 2019-07-18 20:41
Just emailed you the log. Couldn't get it uploaded here for some reason.

**Comment by axxell6307** [comment] 2019-07-18 20:47
That makes sense. Just realized my movie trakt list opens in 10s and it's only the tv trakt that takes along time.

**Comment by axxell6307** [comment] 2019-07-18 20:48
I rarely use my movie trakt list. Sorry, should have specified earlier that it was my tv show trakt list.

**Comment by 123Venom** [comment] 2019-07-18 21:09
Here's an example of the counters.

![Capture1](https://user-images.githubusercontent.com/46383815/61491799-fbadfa80-a97d-11e9-8e2a-3ea6b1c872a8.PNG)

The season counter seems to be fine at the show level but once you brach down to season level it starts to cause lag, damned if I know without verifying api response and logging.  What I'm going to do is remove the season counter except at the show level.  I mean we really don't need that info once we're looking at say a season list of 4 to then go into Info and see a count again of 4?  naaa we can do away with it.  My load time without it went from 14secs to 9.  I also added the caching back in, the bitchin will begin again for the other side of the fence when I do.  Load time dropped to 3secs upon 2nd entry with it cached.

**Comment by 123Venom** [comment] 2019-07-18 21:15
Here's a typical exo fork.  no season, episode or watched counter...no clearart, clearlog, discartt, so that stuff adds load time for more data retrieval.  I already added an option to bypass the additional artwork with the "Disable Extended artwork" option.  Maybe down the road I can add an option tto turn the counters off for people who care more about speed than anything else.
![Capture2](https://user-images.githubusercontent.com/46383815/61492204-d968ac80-a97e-11e9-9b97-52a5fe0a1a92.PNG)

I may get an update out tonight for this and a few other things I've done...after that I'm taking a few days off.  Even been thinking of going dark because the flood of emails and PM's I'm getting from 4 sources is getting a little overwhelming for a one man show.  I got ones from days ago I've not even looked into yet so consider you got lucky

**Comment by axxell6307** [comment] 2019-07-18 21:17
Really appreciate it. Enjoy your time off!

**Comment by 123Venom** [comment] 2019-07-18 21:25
I actually spent 2hrs last night cause this one guy got all messed up playing with the "View Types" and he had no idea how to fix it, not knew what Aftermath was to clear it out.  The current option I have to "Reset View Types" only addresses the Venom "views.db" file but Kodi keeps it's own cache view types for menus you've already visited, based on that addon db file and what you set...so those don't get cleared.  I re-wrote it to now go out and clear out all the cached views from kodi's db file as well so now the "Reset View Types" is global!!!

**Comment by 123Venom** [comment] 2019-07-18 21:33
I have 116 items in my watchlist and it loaded in 18secs, firggin Overeasy did it in 3.  That's actually allot of damn items and wait time for a single page but I need a break as I already got about 4hrs invested in this today just reviewing the Progress list and shaving out 5secs....another day

**Comment by axxell6307** [comment] 2019-07-18 21:42
I hear you man. Don't kill yourself. Be well!

**Comment by 123Venom** [comment] 2019-07-19 01:45
ok I got my 116 item watchlist now loading in 8secs, cached re-entry is 4secs.  To accomplish that I had to add options to disable "Season Count" and "Unwatched Count", those records it gets from your trakt account so by turning them off you're removing api calls and it does speed things up...told ya with more feature comes at a cost like any software.  I could write a book on how older software runs faster on a newer pc, but you get the point.  Basically flipping all the enhanced features off that I've added for the last 6 months...lol.  For the hell of it I cleared cache, yet again, and disabled Extended artwork and got the load time to 7secs.  Least yall will have that choice now of speed vs. info and wow factor.  Me I'm leaving them all on and use a watch list from widget, which is plenty fast for me.  I hate that trakt shit in "My Lists" cause the code is butt ass UGLY!!  It needs a re-write!  Just doing some tests to make sure it's good to roll and should be out tonight.

**Comment by 123Venom** [comment] 2019-07-19 01:53
Holly shit!  with all these feature now turned off I'm getting some of my TMDb menus now loading in 2secs after a full cache clear.  I also use the Page Limit option set to 10.  I'm even shocked the impact extra api calls is having.

**Comment by SoulTV** [comment] 2019-07-19 03:03
Been watching this thread for a bit now. I REALLY like all of the extra info (season count, episode count) and extended artwork that Venom provides, especial when using Titan Bingie. All the extra meta allows Titan Bingie to add these "new episode tags" which no other addon does well. All to say, can all of these changes be made into options/toggles in settings instead of being entirely removed??

Also appreciate all of your work on Venom! You and Nix are killing it

**Comment by 123Venom** [comment] 2019-07-19 17:51
Adding options to disable is exactly what i did.  I was pretty clear I was not going to undo my last 6 months of work.

I'm in no way in Nix's class.  Code rolls off that mans tongue like it's memorized.  He's a HUGE asset to the community and he's assisted me with Venom more than once.

**Comment by axxell6307** [comment] 2019-07-19 17:52
Love your attitude and having you in the community also. Thank you.

**Comment by ricklepick** [comment] 2019-07-19 21:27
Great news (the speed and options). I don't care for any of the extra visual buzzers and bells myself.  Just want it fast, fast, fast getting to playback (that's why I'm in Kodi, after all). Letting the user choose is always best though because others do love these enhancements and like you said, why undo 6mo of work? <g>

Thanks for working so hard on this V.

**Comment by 123Venom** [comment] 2019-07-19 21:40
has anyone tested the version I pushed last night and shut off all the bells and whistles to note any speed differences?  I had Trakt Progress shave 10secs off the load time with all disabled.  I do think History still sucked but I'll spend some more time on that later...who even uses the History?..kind of why I didn't invest more time once I saw that load time crumble and thought not a high priority to hold off pushing the update.   Seems watchlist and progress are the two most used.

**Comment by axxell6307** [comment] 2019-07-19 21:47
I got the update and toggled off season counter and it did not affect my speeds. I think I'm an outlier here. Don't worry about it man. Just glad to have a working addon.

**Comment by ricklepick** [comment] 2019-07-19 21:51
I have not tested yet. Will do in a few hrs.  I use Watchlist and Progress pretty much exclusively.

**Comment by 123Venom** [comment] 2019-07-20 01:36
> 
> 
> I got the update and toggled off season counter and it did not affect my speeds. I think I'm an outlier here. Don't worry about it man. Just glad to have a working addon.

I'm shocked to hear that after I posted results what I saw.  Wish I could get my hands on that device...I'd find it.  You cleared cache right?  I'd even give AfterMath a try and purge all Kodi databases.

**Comment by 123Venom** [comment] 2019-07-20 01:50
Here's something I just changed, and surprised nobody has ever commented and asked why some Trakt lists are different than a typical exo fork.  The 1st pic is my typical displayed list of items.  I had to fake out the system and tell it that it's a "seasons" list so your unwatched counters would show up.  This causes your usual thumbnail to show poster art instead, as well as the studio logo...didn't bother me.  See the number in the box...that's the number of unwatched episodes for that show.
![Capture2](https://user-images.githubusercontent.com/46383815/61572576-df898680-aa6d-11e9-85d8-44618e57a779.PNG)

Now in the next pic say you turn off "unwatched count" there's now no reason for me to fake it out to think it's a season list so I resorted back to the old "episode" list when that option is turned off.  I don't know I was bored I guess.

Also I found another item I can flip off if you do not enable UpNext.  UpNext requires IMDB_ID, TVDB_ID etc. for the episode.  Exo forks do not gather these ID's so I wrote a very small function for an api request to get those ID's and they're only needed for UpNext so if the option is not enabled why waste the api request and add time right.  I didn't need any setting opttion for that, just an added check if UpNext is enabled or not to skip the api request and null out the values.  I got my own load time down to 5secs with that change after a fresh cache clear, and 3secs upon reentry.

**Comment by axxell6307** [comment] 2019-07-20 13:36
> > I got the update and toggled off season counter and it did not affect my speeds. I think I'm an outlier here. Don't worry about it man. Just glad to have a working addon.
> 
> I'm shocked to hear that after I posted results what I saw. Wish I could get my hands on that device...I'd find it. You cleared cache right? I'd even give AfterMath a try and purge all Kodi databases.

I did clear cache. Does Rock cleaner purge all of that? I have Rock. I can try AfterMath. It's just an addon right, not a build?

**Comment by 123Venom** [comment] 2019-07-20 17:08
I've never used rock cleaner so I cant say

**Comment by iCanuck** [comment] 2019-09-06 04:51
First off thanks Venom for updating a lot of the exo code, I have went through most of it and you have added/fixed alot! but I have to agree trakt loading is an issue on slower (but still capable) devices. I mainly use S905x & S912 devices running CoreELEC but I also use Venom on windows. Windows has no problem running Venom but the AML devices are significantly slower loading trakt pages (eg. People Watching). I have forked many exo addons in the past so I know the code in and out... I have played around with much of Venom's code and I can't seem to speed up trakt pages. Even after reverting most of the changes done to any of the trakt code it still does not speed up (I'm sure I am missing something). Venom has so much potential with all of your added functions and fixes but I cannot get over the slow loading of trakt pages as I mainly use People Watching and Progress.

P.S. there is an issue with your extrainfo code in the sources module. It is not displaying correctly, I will try and do a PR to fix when I have some free time but it is right between line#1145 & 1175. Also I have ported the Lazyman2 addon over to work with Venom, if you would like me to share the code with you let me know. It is as simple as adding some actions, a couple modules and the icon folders for networks / teams.

**Comment by 123Venom** [comment] 2019-09-09 00:08
Funny you mention reverting back to original code as i did allot of that same testing and was left stumped that no real speed up seen.

I just completed some changes to Trakt lists were I had previously switched to using trakt pagination but was unaware of a sort issue in the api response and it's serving up random items, unless the full list is requested.  This forced me to revert to old method and testing some other caching methods.  I hope to get that pushed tomorrow.

I'll gladly have a look over your extrainfo mod.  It's sure nice to get a little help as some days i get overwhelmed with requests for changes.fixes and being a one man show makes it tough.

I'm not familiar with the Lazyman2 addon but I'll check it out when I get a chance and consider adding it if worthwhile to do so...thanks and appreciate you investing your time in this.

**Comment by 123Venom** [comment] 2019-09-09 17:49
I think what I may experiment with later tonight is grouping some cases of
start = time.time()
end = time.time()
and see if we can track processing time and wth is causing the lag be it api request or meta variable assignment.

**Comment by iCanuck** [comment] 2019-09-10 01:43
Would it be helpful to do a PR for the extrainfo fixes? or I can push my fork to my
other github, this way you can see the Sports section as well.

Sounds like a good experiment... I seem to think it has to do with the meta as I disabled it entirely by removing some code and trending takes about 1-2 seconds.

**Comment by 123Venom** [comment] 2019-09-10 02:11
ya you can PR the extrainnfo and I'll look at it...haven't had the chance yet.  I reverted back to non paginated trakt list and still tweaking some stuff.  Allot of unnecessary encoding or use of replaceHTMLCodes().  What puzzling me is their expectation there's html codes in an api response...seen it maybe once in tvmaze's api so I'm testing nearly line by line and logging to clean this up and shrink the code but scrapping just took a dump on me so doing more head scratching.

**Comment by 123Venom** [comment] 2019-09-10 03:09
I had a super quick glance because scrapping took a dump on me and as you know sources.py general culprit.  I jumped right to the line you mentioned and see this...

`if multi is True and l != 'en':`
 Looks good to me as,  I = self.sources[i]['language']
I then checked other exo forks and see they use
`if multi == True and not l == 'en':`

My preference is "is True" vs "==" as I switched this method some time ago due to a number of different articles claiming == for True, False, or None can fail and best to use "is" vs. "==" as it's also faster.  I also prefer to not use a statement like `and not ? ==` but better to use `!=`.  Other than that raising a question I'm not seeing anything wrong with that first line you stated.

**Comment by 123Venom** [comment] 2019-09-10 06:00
Now here''s something interesting.  So I started adding some timed processing to see where the lag may be.  In the attached I just logged the first api request to my Trakt progress list.  Then I logged what that same call is but from the cache..looks crazy faster right?
![Capture](https://user-images.githubusercontent.com/46383815/64587561-cf0ad380-d36d-11e9-86d0-9f8fb58b8ab7.PNG)

I timed it also by stop watch so the stop watch was start/finish full api requests and dir load times to display in skin.  I got 5.5secs to fully load my trakt progress of exactly 81 items.  It took 3.5 secs to load that same list subsequently from cache file...something looks strange in real world numbers vs. a stop watch.  I'm going to keep breaking it down with time.time() per phases, or api request and see what it looks like but it's already turning me off a bit

**Comment by 123Venom** [comment] 2019-09-11 06:06
Think I may be onto something checking time duration to complete defs in steps.  My context menu items in episodeDirectory() is chocking the hell out of speed.  Full def completed in 3secs compared to a typical exo fork did it in .6secs.  I started to then break the code down into sections to find where this bad lag is.  Context Menu items!!  I even tried commenting mine out and the speed cut down to near identical of an exo fork.  Not sure there are known limitation to number of context menu items but it's looking like this is one bad culprit.

**Comment by 123Venom** [comment] 2019-09-11 07:16
FOUND IT.  Take a hard look where I have indicators = playcount.getSeasonIndicators(imdb).  Let me know what you see that is wrong. hint...only needs to execute once but where is it!

**Comment by 123Venom** [comment] 2019-09-11 08:28
just pushed v3.1.9 and trakt lists are now loading ALLOT faster on my end.  Anyone still following please let me know how this now works.  Sorry to say I found a very bad goof on mine and while it won't error out it did loop unnecessarily and caused allot of lag calling a function multiple times when it did not need be.

**Comment by 123Venom** [comment] 2019-09-20 08:08
closing this as I've adjusted about all I can

**Closed by 123Venom** 2019-09-20 08:08 UTC

**Comment by iCanuck** [comment] 2019-09-23 00:51
Sorry to be inactive for a long time there, I was out of town for work for a while. I have quickly looked at your changes and tested v3.2.0 and I can confirm the load times are fixed! Great job. 
I will try and do a PR for a few things in the next few days, I have had zero free time lately.

**Comment by 123Venom** [comment] 2019-09-23 01:21
I'll keep a watch out for PR..thanks
