### ISSUE TITLE
Trakt new episodes not populating if specials have been watched

### ISSUE THREAD

**Issue by Gobberwart** [123Venom/plugin.video.venom#45] opened 2020-03-22 09:15 UTC
I recently (a couple of months ago) switched from exodus redux to venom, and generally much prefer it, however I noticed that a few TV shows refuse to show in new episodes.

After some fiddling, I noticed that the missing shows all had "special" episodes (season 0) which I had marked as watched. Likely because they are shows I had seen well before trakt existed so I just marked the whole show as watched to catch up. 

If I mark season 0 as unwatched, the shows come back and work correctly. 

I remember fixing this specific bug back in the days of exodus (not redux). I can't recall specifics but it was caused by the addon getting the watched episodes count (including season 0) and comparing against the available count (excluding season 0). If watched was greater than available, it would just assume that meant it was up to date and didn't show any new episodes.

Looks like this bug has crept back in.

**Comment by 123Venom** [comment] 2020-03-22 19:14
Perhaps a show where this happens to you?  I tested the first two items in my own list, Altered Carbon, and The Good Wife.  After marking Season0 as watched both shows remained fine here.  I did spot that Altered Carbon was now listing 1x01 as next and that is wrong and should be 1x10.  If I go back and unmark Season0 it returned to 1x10, which is correct.  A few months back I changed the code to address a TVDB v1 api change where they mucked with the order of items in the api response and it severely broke this list.  Prior to their v3 api rollout the season/episodes always went in order so we just grabbed the next item in the index.  Once v3 api rollout took place they changed the sort order of the v1 api to now be based on the ID of the episode.  Most exo forks are still grabbing the next indexed item and it does not work.  The cure was to resort the entire xml file and after seeing it's behavior with Altered Carbon something is still off I need to review.  The Good Wife behaved fine marking Season0.  I can't seem to make shows vanish here though so give me a case of this and I'll check it.

**Comment by Gobberwart** [comment] 2020-03-22 20:02
Qi, simpsons, family guy, ncis, ncis los angeles.

**Comment by 123Venom** [comment] 2020-03-22 20:59
I'll check into those shows.  In the mean time I had a peak at the issue I spotted with Altered Carbon.  The trakt api placed season0 at the end of the full watched list while The Good Wife it place season0 at the beginning, where it belongs!  So Altered Carbon listed Season1 then Season0. So when it checks the index it sees the last item watched was Season0x02 so in the interface it shows Season1x01 as next to watch.  Even though I know that's wrong it's correct in how the api responded.  I have no idea why the api would do that but in this instance it's clearly a trakt issue.  The only way to solve it is to also sort the response from trakt.  The sort issue I spoke of that I previously solved was due to TVDB's response also being out of order and now I'm seeing it with trakt as well.  Shit gets really frustrating.

**Comment by 123Venom** [comment] 2020-03-22 21:03
do you have Season0 turned off from being displayed?

**Comment by Gobberwart** [comment] 2020-03-22 22:55
I do have season 0 turned off. I tend to find I get no usable sources for special episodes so I just exclude them. I turned them on temporarily and saw no change in behaviour.

**Comment by 123Venom** [comment] 2020-03-22 23:25
well that rules out that idea.

Anyway so now that I discovered the trakt api at times responds back with seasons out of order, like TVDB, I just added a sort function for the response and it cured the issue I had with  `Altered Carbon` as such.
[https://i.postimg.cc/ZRqFzgvz/Altered-Carbon2.png](url)
left is before new sort function of trakt api response.  Right is with new sort.  It also has no negative effect on the api responses where order is not an issue.

I'll experiment with one of your listed shows and see what I get.

**Comment by Gobberwart** [comment] 2020-03-22 23:38
Cheers mate, really appreciate the effort. I can work around it but would be nice if it just worked despite the trakt api being a steaming pile of shit.

Because hey let's implement a new api but also break the old one while we're at it!

**Comment by 123Venom** [comment] 2020-03-22 23:40
hmmm...so I picked your NCIS: Los Angles.  First I marked S1x01 as watched..then checked listing and 1x02 was first on list.  Then I went back and selected Season0 and marked ALL as watched...returned to list and the show still shows me 1x02 and it does not vanish here.  I can't duplicate it.
[https://i.postimg.cc/3JwC5c6Z/NCIS-LA1.png](url)
[https://i.postimg.cc/wT3Jbsyf/NCIS-LA2.png](url)
I also tried this with and without the new sort feature I added to fix trakt's api issue and no change so this particular show doesn't suffer an out of order....that `Altered Carbon` show might have been a rare case but glad i spotted it cause i got a fix to address it if it does indeed happen elsewhere.

What's the last marked episode as watched on your list for NCIS: LA?  I'll try to get it exact to yours see if anything changes.

**Comment by 123Venom** [comment] 2020-03-22 23:42
ha..looks like external links don't work here on gh?  I clicked one I posted and it seems to be looking on gh so it throws an error.  You can copy/paste them into address bar...sorry wasn't aware externals were an issue

**Comment by Gobberwart** [comment] 2020-03-22 23:58
Interesting... It's possible I marked those shows as read through trakt rather than through a kodi addon. As in, I went to trakt, found the show and just marked it all watched, then marked any unwatched episodes (probably only 2 or 3 at the time) as unwatched. Let me experiment a bit and see if I can reproduce the issue myself.

**Comment by 123Venom** [comment] 2020-03-23 00:00
honestly that shouldn't matter because when I make my trakt api request it still should match no matter if you marked at site or from the addon.  Something else must be triggering this

**Comment by Gobberwart** [comment] 2020-03-23 00:13
Ok, working with the show QI

To try and get progress working I had previously marked seasons 0, 1 and 2 unwatched and it was showing the correct info in new episodes. 

Marked season 0 as watched (using the trakt website), and found "new episodes" was still ok.

Marked season 1 as watched and qi disappeared from "new episodes".

Trakt now shows that I've watched 264/272 episodes..

So, I "unwatched" 9 episodes.. 

QI appears again in "new episodes" 

Marked one as watched... QI is gone from "new episodes" 

Seems to me like a counting error in the addon.

Eg. 

Available episodes (excluding season 0) = 265
Watched episodes (including season 0) = 266
Watched is greater than available, so venom thinks there's nothing to see and doesn't include the show at all.

**Comment by Gobberwart** [comment] 2020-03-23 00:18
A bit of pseudocode...

If (specials enabled) {
  Watchedcount = all watched
} else {
  Watchedcount = all watched except specials
}

**Comment by Gobberwart** [comment] 2020-03-23 00:23
Suggested testing..

Mark the whole show as watched, then just mark one unwatched, check new episodes. Repeat until the number of unwatched episodes is >= number of special episodes. I expect the show to be gone until the number unwatched is greater than specials.

**Comment by 123Venom** [comment] 2020-03-23 00:41
Not sure where your count of 266(including Season0) comes from?
<img width="400" alt="Capture21" src="https://user-images.githubusercontent.com/46383815/77268504-8c12ac80-6c7c-11ea-93ad-107a0e404e31.PNG">
That's including Season0.  The trakt web site lists 302 total, difference of 14 vs. the api. Season0 the api is only responding back with 16 episodes while the web site says there's 30..a difference of the 14 I'm missing in the interface.
<img width="400" alt="Capture22" src="https://user-images.githubusercontent.com/46383815/77268648-02afaa00-6c7d-11ea-8dc2-0533624c8986.PNG">

I'd have to log all that data from trakt..then log all from TVDB to see if they match because the whole list is made up from requests to both.  

You point fingers at the addon but my bet says i log all this data I'll find it in the api

**Comment by 123Venom** [comment] 2020-03-23 01:01
Just looking over TVDB's site info for a quick check and they're missing release dates.  Notice the gap that 13-15 is dropped?
<img width="1132" alt="Qi_1" src="https://user-images.githubusercontent.com/46383815/77269433-3d1a4680-6c7f-11ea-9664-0158d8670a46.PNG">
That's why the Season0 count is off, so it's not what you think it is,  because with no release date I'm sure it's also missing in the api and breaking shit.  I'm looking at a work around.

**Comment by Gobberwart** [comment] 2020-03-23 01:31
Ok, just interesting that I can reproduce the problem by marking exactly 1 more than available episodes minus special as watched.

**Comment by 123Venom** [comment] 2020-03-23 01:50
I'm sure that would reproduce it.  I didn't mark all that and didn't have to, I just reviewed the count mismatch and knew where the issue was and went to hunt down why.  You stated when this happens hitting that mismatch count so that was enough for me to know the trigger...less I shouldn't have trusted you?..lol.  The count is off because of episodes missing premiered dates so they're dropped.  Just open Season0 and compare to TVDB and you'll see it.  When you reach that mismatch count is when you hit the problem.  I also just checked two other exo forks and all report the same Season0 count and those 14 missing episodes are the issue.  Even if I was to incorporate a work around to fix TVDB's problem take notice that trakt reports 30 episodes for Season0 but TVDB reports 28.  You'd still have this issue when you hit that mismatch again.  You could report the issue on TVDB's site of the 14 missing releases dates and 2 missing episodes.  If they fixed that this issue would go away.

The other thing you could do is unmark the shows Season0 where this happens, especially since you turn off Season0 anyway right?  Then it shouldn't account for those

You still didn't tell me how you got 266 for a count..no data I have for that show adds to that.

**Comment by Gobberwart** [comment] 2020-03-23 01:59
Oh I probably just gave a wrong number. I just meant to say that number of watched episodes including specials was greater than number of available episodes excluding specials..

I can work around by just marking season 0 as unwatched.

**Comment by Gobberwart** [comment] 2020-03-23 02:01
Did you fix the issue?

**Comment by 123Venom** [comment] 2020-03-23 02:02
ok now I'm rethinking your count mismatch analysis and thinking your wrong bout that also...damn knew I should have believed you..lol.  Here's how it actually works.  The trakt api responds back with a full list of watched episodes...generally in order but as noted with `Altered Carbon` the damn Season0 was at the end and not the beginning, but that's now fixed with a workaround for the out of order issue.  Lets say last episode you watched was 17x03.  That episode should appear at the very end and I grab the last item with [-1].  We get minimal show info from trakt with this watched list api request so a TVDB request is then needed.  I take your last item watched and fetch the next item in TVDB's index.  Best way to see what's really happening is give me the exact last episode you have marked...I'll duplicate it here and then I will log the api response and see wth is shown.  Honestly the total count should not have anything to do with this.  Where the  mismatch count might break it is if the next episode was dropped due to missing premiered date like you saw...then the next item is not available and dropped.  Since QI has dropped episodes in Season0 I'm wondering if Season0 is at the end and it's trying to grab and index there and the episode is dropped.  If that happens to be the case the little fix I did to resort trakt api response would fix it

**Comment by 123Venom** [comment] 2020-03-23 02:06
>>Did you fix the issue?<<
I told you what issue I did fix.

**Comment by Gobberwart** [comment] 2020-03-23 02:47
Not sure what else you need. If I have 'include special episodes' disabled, and I've marked some special episodes as watched then if I've watched more episodes (including specials) than are available (excluding specials) , venom doesn't show them.

**Comment by Gobberwart** [comment] 2020-03-23 02:48
I'll retry with ncis and see if I get the same result.

**Comment by 123Venom** [comment] 2020-03-23 03:05
Don't need anything else.  I found a cure for the mismatch through some logging I just performed to see the issue is purely in the trakt api count.

Closing this and fix will be pushed...that was a shit ton of tracking hours.

**Comment by 123Venom** [comment] 2020-03-23 03:06
I'll upload a version to my dev brach..test and see if it fixes the issues.

**Comment by 123Venom** [comment] 2020-03-23 03:22
I've uploaded v3.5.6a to dev branch only.  Download and test that.  I marked that QI show to 17x02 and it vanished.  Upon adjusting the count for season0 consideration it came back so that should fix it.

**Comment by 123Venom** [comment] 2020-03-23 03:25
there's actually 2 fixes in that version.  That count issue and the re-sort for cases where trakt api seems to want to put Season0 at the end of the watch list and not in beginning.  That fixed the `Altered Carbon` issue I saw while checking your issue and I'm sure it's not the only show they accidentally do that to.

**Comment by 123Venom** [comment] 2020-03-23 05:11
?

**Comment by Gobberwart** [comment] 2020-03-23 05:26
Calm down... My family is now using the TV so I have to wait until I can test again.

**Comment by 123Venom** [comment] 2020-03-23 06:31
umm I waited and you didn't reply and I spent my free time all over helping you for hours today for api issues that were not mine, yet you did in fact blame me.  Least you could have done was said that that 2hrs ago.  Check the time stamp!  You want me to calm down...next time find another addon and fuck off!  Closed and blocked!

**Closed** 2020-03-23 06:32 UTC
