### ISSUE TITLE
download  missing from options menu. 

### ISSUE THREAD

**Issue by ghalex1245** [123Venom/plugin.video.venom#78] opened 2020-09-09 07:51 UTC
download opion missing from options menu. used to be visable. no longer visisble the plugin settigs still have the download section enabled with folder paths. once source is located the options menu doe not show download.

**Comment by 123Venom** [comment] 2020-09-09 10:16
Shows up fine here.
[13.png](https://postimg.cc/KkXgJWzk)

I have however made significant changes to Venom and that test was on my dev pc and I did not think I've touched that.  I just checked my laptop where there's an untouched official release installed.  Low and behold it's missing so looks like I have fixed that.  I'm a few weeks out of a major change so I'll see if I can do a separate fix and push and update to get that context menu option back for you.

**Comment by 123Venom** [comment] 2020-09-09 10:37
After comparing the code on my dev pc to the official release of v4.1.2 I did not find anything I changed...then it hit me I never use downloads on that laptop and as fait would have it they were not setup.  Once I enabled `Downloads` and set the folder paths the `Download` context menu now appears.  Sorry but I'm not seeing an issue here.  Please post a screenshot of you `Download` settings and then a screenshot of the condition where it will not show up.

**Comment by ghalex1245** [comment] 2020-09-09 23:00
on the firstick. screenhot but from reedit sems like other are expriencing this also https://www.reddit.com/r/Addons4Kodi/comments/innlao/cant_see_a_download_option_in_venom_or_the_crew/. maybe only happnes on portables like firestick or raspi?

**Comment by 123Venom** [comment] 2020-09-09 23:25
Ya man sorry I do not do reddit, deleted that account some time ago.  I think I just duplicated the problem.  When I flipped on **COUGH** free hosters I can see resolving to download is broken and the option is missing from context menu for those sources...are you using free hosters?  Torrents are no problem and 99.9% of what I do are torrents only.  I was able to fix it but I'm letting you know that free hosters are soon to be completely removed from Venom support as I'm half done it's removal now.

**Comment by ghalex1245** [comment] 2020-09-09 23:30
ohh ok good to know the reson why. thought it was just a specific issue for few of us. thanks for the quick response.

**Comment by 123Venom** [comment] 2020-09-10 01:36
I pushed v4.1.3 and the issue is fixed locally here for free hoster downloads.  Beyond that version the offering will no longer exist.  I suggest the following.....

1.) A Premium Account, whole new world of links I personally could never go back to free hosters...EVER.
2.) Disable Auto Updates in Venom and Openscrapers.  Although OpenScrapers is not official yet that free hosters are being removed.  We may opt for an OpenScrapers2 so other devs want to support free hosters still can.
3.)  The Crew is a good option and still supports free hosters, I believe they still even maintain them, although god himself can't beat Cloudflare V2 challenge without some coin spent...lol

Sorry!

**Closed** 2020-09-10 01:36 UTC
