### ISSUE TITLE
v3.2 tvshows.py SeriesName

### ISSUE THREAD

**Issue by bjbca** [123Venom/plugin.video.venom#19] opened 2019-09-25 12:29 UTC
Hi, thnx for the update, still dont like clearart so i just used the player that i modded from last ver...
new issue since change in tvshows.py then in tv show searches some titles will come up blank though there will be show info, i believe it is the code changes in ###--Check TVDb for missing info old code line at 1047 new line 1043 for title = client.parseDOM(item, 'SeriesName')[0] need title = client.replaceHTMLCodes(title)

**Comment by 123Venom** [comment] 2019-09-26 00:06
Honestly that is by design of the Estuary skin and got my answer on the kodi.tv forum bout this issue.  They move the season/episode info over and title is removed since it's in the tvshow.clearart.  Only thing I could do to cure your dislike of the design is perhaps add an option like "enable clearart/clearlog in player". 

 I'll look at your other issue more indepth when I get a chance but I don't recall touching that code.  That's fetching meta from TVDb v1 api...you sure "SeriesName" is not in the xml response?  Did you test it?  I had a quick glance at a few exo forks, Gaia included, and all use "SeriesName" from that xml response.  I'll have to test this when I get more time but if you're right then they're all doing it wrong so I'm a bit suspicious on you being correct here.

**Comment by 123Venom** [comment] 2019-09-26 00:17
sorry..being in a rush I misread what you're saying, always running like a chicken with my head cut off.  I cleaned up allot of the cases of the use of that r.eplaceHTMLCodes() and if you look real close at exo forks they were using this even in an api response.  I've yet to log and see html codes in an api so imo that's wasted processing time...however...in this case this is TVDB's v1 api and the response is a .xml file which very well may contain html codes, but still suspicious I am because I thought I logged and checked that when I did code cleanup.  I'm going to log and test the response when I get more time and see.  It's either that or I got a little happy and removed a case that needed it.

**Comment by 123Venom** [comment] 2019-09-26 00:33
I said f'it...only take me a few minutes to log the response and have a look.  Took me a few gapes to find a case but it is..html codes in that title and should be in there for that case.  I'll add it..nice catch!

![Capture50](https://user-images.githubusercontent.com/46383815/65649197-8ab93d80-dfd3-11e9-9aea-3b726442f060.PNG)

**Comment by 123Venom** [comment] 2019-09-26 00:51
looked over a shit ton off data and, check me, but looks to me that the following tags are the only ones that occasionally contain html codes.

<Actors> I no longer use
<SeriesName>
<Overview>

I did leave it for <Overview> but removed it for <SeriesName> so again I either got carried away or during my initial logging test I didn't go enough pages to deep to encounter a case so as for now, "It's getting added back" to just <SeriesName>

**Comment by 123Venom** [comment] 2019-09-26 01:27
and because you drew my attention back to this issue my new use of ElementTree needed it for both name and roll so some actors were getting dropped.

**Comment by bjbca** [comment] 2019-09-26 12:20
Nice work on player ;)
Im still having trouble with tvshows.py, havent had time too chk the code but i will try upload screen shots of an example search:

**Comment by 123Venom** [comment] 2019-09-26 18:49
that looks like an issue coming from the InfoLabels...in the directory list builder.  I'll have to check and see on that title and what's up with it.

**Comment by bjbca** [comment] 2019-09-27 02:53
something is just not quite right, if i put the tvshows.py from v3.19 into v3.21, clear all cache, then the search results show the proper name listings:

![](https://github.com/bjbca/redone/blob/master/tv.test.riviera.3.png)

**Comment by bjbca** [comment] 2019-09-27 03:24
Lots of this in the log using v3.19 tvshows.py :
[2019-09-26 21:18:48] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.menus.tvshows.super_info() Line # :1095
                       msg : actors = <?xml version="1.0" encoding="UTF-8" ?>
<Actors>
<Actor>
  <id>390762</id>
  <Image></Image>
  <Name>Richard E Grant</Name>
  <Role>Narrator</Role>
  <SortOrder>3</SortOrder>
</Actor>
</Actors>

**Comment by 123Venom** [comment] 2019-09-27 09:36
I told you I'd look at it didn't I or is there a listening problem here?  Secondly the line you posted is nothing but an indication i left logging string in a release that i was trying to check data..you see an error there? Chill out buddy and lay low till I do what I told you I would.  I'm 200+ frickin miles from home for two days but seriously did not think I had to explain myself.  This bullshit continues issues will be turned off..lastly venom will get moved to private server so relax and wait your frickin turn

**Comment by 123Venom** [comment] 2019-09-27 10:15
And lets point something else out to you.  Your first issue was due to Estuary expecting tvshow.clearlogo vs. clearlogo..i fixed it for you but was not good enough.  For some reason the show title being in the clearlogo bothered you and you preferred to see the text name...nuts ya ask me but i bit and changed that for you as well and added option to turn off that artwork in the player. Then you give me zilch time to look at your next complaint?  Bud seriously if you go back your original complaint i told you I'd look at it yet followed up immediately.  Do you know what that means? Means i stopped working to address your complaint and from here on out that shit stops as its obviously not enough

**Comment by 123Venom** [comment] 2019-09-27 10:22
So issue now moved to back of pile, if I even chose to waste another ounce of my free time on pesky people who refuse to listen.

**Comment by 123Venom** [comment] 2019-09-28 05:26
looked at and now fixed so closing.

**Closed by 123Venom** 2019-09-28 05:26 UTC
