### ISSUE TITLE
IMDB watchlist not displaying plot for TV shows

### ISSUE THREAD

**Issue by Zero3ffect** [123Venom/plugin.video.venom#51] opened 2020-05-05 00:34 UTC
I'm sure most people don't really use the IMDB watchlist but for some reason it doesn't display plot information for TV shows (just the show itself, the episodes are fine as are movies).  If the show information was cached via another method (like searching) prior to going into the IMDB watchlist the first time, it will display the plot but otherwise it will be blank.

**Comment by 123Venom** [comment] 2020-05-05 21:46
confirmed!  Looks like IMDB changed their class tag on the plot.  It's fixed and will be included in next release.

**Comment by Zero3ffect** [comment] 2020-05-05 22:31
Awesome.  Thank you very much!

**Closed** 2020-05-07 19:15 UTC
