### ISSUE TITLE
Multi line source list

### ISSUE THREAD

**Issue by diemenz** [123Venom/plugin.video.venom#14] opened 2019-09-11 23:37 UTC
With the last update this is now defaulted on without ability to turn off when using directory. It makes reading the source info extremely difficult on an Apple TV.

**Comment by diemenz** [comment] 2019-09-14 00:42
That is crazy weird. I wonder why it she’s that way in two of my Apple TV’s. I even tried a full fresh install. I’m racking my brain trying to think what I might have done to cause this.

**Comment by drinfernoo** [comment] 2019-09-14 01:16
@diemenz What skin are you using? It shouldn't make any difference, but may help point to what is wrong.

**Comment by diemenz** [comment] 2019-09-14 01:17
I am using Aeon Nox Silvio. No other Addons seem to do this. It’s not a deal breaker it’s just not as pretty haha

**Comment by drinfernoo** [comment] 2019-09-14 02:24
Can you replicate the issue in Estuary? There really should be no reason why the setting wouldn't be functional.

**Comment by 123Venom** [comment] 2019-09-14 08:53
Pics I showed were from Silvo, and tough to say no other addon does this when only two exo forks ever introduced multi-line label, one was Venom and other was Overeasy, Venom had it first so what addon you claiming to compare when no other currently does it?

**Comment by 123Venom** [comment] 2019-09-14 08:55
Doesn't make a a lick of sense to me comparing what no other exo fork does multi-line label so please explain that claim

**Comment by 123Venom** [comment] 2019-09-14 09:25
>>No other Addons seem to do this<<  I'll let you in on a little secret to answer that.  The reason no other addon does this is because no other addon does multiline label..Venom is only exo fork that does it.  Waiting patiently to hear what you compared it to.

**Comment by Mr-invisibles** [comment] 2019-09-14 13:50
sorry but some exo forks does it better, seems better to me..
![20190909_175536](https://user-images.githubusercontent.com/49566461/64909039-4d1d0080-d707-11e9-8868-2b4d3d5bd4ac.jpg)

**Comment by Mr-invisibles** [comment] 2019-09-14 13:51
but would be nice if you updated so it looks like this.. can send link to the add-on

**Comment by diemenz** [comment] 2019-09-14 13:59
I am sorry my goal was not to cause any drama or upset anyone. When I said no other add-on seems to do this i was referring to multiline. I don't use any other add-on that does multiline, there might be some out there like invisibles posted but I don't have one that does so thats why i said it.
 I am not saying multiline is a bad thing I was just wondering if it was something I did or something I changed to cause it because one day it was single line and the next day it was multiline and greyed out so I cannot change it.

**Comment by drinfernoo** [comment] 2019-09-14 14:37
@diemenz Just turn it off:

![](https://i.imgur.com/npQMeRO.jpg)

**Comment by diemenz** [comment] 2019-09-14 14:58
As mentioned in my last post and the original post the option to turn it off is greyed it and not changeable. I wish it was that easy :) haha
https://imgur.com/a/mhaN1bw

**Comment by drinfernoo** [comment] 2019-09-14 15:31
@diemenz What I believe you need to do is delete the file at `special://userdata/addon_data/plugin.video.venom/settings.xml`.

This will revert your settings back to defaults, so you may need to make a few adjustments, but will also negate the chance of conflicting settings from old versions.

**Comment by diemenz** [comment] 2019-09-14 16:39
I did try that and it didn’t work. I decided to do some digging and noticed that this seems to be an issue with Apple TV. 
I did fresh installs on 3 different devices and only the Apple TV comes up with this issue and it does so right off the bat. I know there is some issues with a few other addons and the Apple TV so I am going to assume this is similar.

**Comment by 123Venom** [comment] 2019-09-14 16:45
Send me the link..that's a first I've seen and do not even recognize the addon.  I see format and color differences if those are big deals to you.  Sorry if I came off little rough I just get frustrated over stuff I can't reproduce and don't like it thrown at me how "other addons dont do it" or as you more recently stated, "do it better".  If you found something that does it better perhaps you already had your answers.  Option not greyed out here and never seen nor heard of that happening

**Comment by diemenz** [comment] 2019-09-14 16:50
It’s not greyed out on my fire TV out my iPad so it is defiantly Apple TV related. The Apple TV is using a “beta” version of kodi as it’s not officially released and there occasionally is some visual issues. For example Gaia’s fancy menus for sources and directory will not even display on the Apple TV. They will at first but after you close kodi they will not work again. I have no clue why but it’s been an issue for as long as I can remember.

**Comment by 123Venom** [comment] 2019-09-14 16:58
Did you try flipping through the "Default action" setting?  Multiline I only allowed with directory...no point in autoplay and dialog I felt would be to ugly.  I see your on directory in your pic but as the good dr mentioned it could be a skin issue but you could very well be right though..Apple TV issue...not something I'll ever touch.

**Comment by diemenz** [comment] 2019-09-14 17:20
I checked it out with estouchy and estuary and it is grey out for both of those skins too so I’m going to guess this is Apple TV. I checked auto-play and dialog and it stays greyed out.  I thought back and realized I haven’t actually looked at sources in at least a month previous to this as I normally watch TV and have up next enabled and it goes to auto-play so this could have happened a while ago.  
It doesn’t ruin the experience it is just formatted funny in this skin. 
https://imgur.com/a/ZcKajZT

**Comment by 123Venom** [comment] 2019-09-14 17:27
Sounds like another reason to add to my list of why I dont use Apple Tv..sorry man wish I had the answer but sounds like even gaia is not functioning well on Apple TV

**Comment by diemenz** [comment] 2019-09-14 22:02
Its actually a great device for media streaming your own content, I use Kodi mostly as a media player for my own rips but occasionally go looking for a tv show i missed or similar. there is some hurdles to get over when it comes to installing it but once you are there it is smooth as butter :)

**Comment by 123Venom** [comment] 2019-09-14 22:32
I'm to hooked on a shield to prob ever switch.  I have a htpc setup in living room with a 16tb eSATA media storage.  Streams to shield great.

**Comment by drinfernoo** [comment] 2019-09-14 22:48
@diemenz There hasn't been a new build for Kodi since February 2018... no wonder you're having issues. Is it even Leia 18.x?

**Comment by diemenz** [comment] 2019-09-14 23:49
Venom that's a pretty crazy setup. I just have a Mac mini running an array. 
Dr that is the only version that has been compiled. They are working merging tvOS into 19 but the timeframe isn’t defined.

**Comment by 123Venom** [comment] 2019-09-19 02:18
closing this one...issue is related to Apple TV.  Next update I will be releasing a new multiline layout with secondary line color option and some new formatting to help it stand out.  Also tweaked the info identification of scraped titles.

**Closed by 123Venom** 2019-09-19 02:18 UTC

**Comment by diemenz** [comment] 2019-09-19 02:23
Does the new formatting impact font size on the second row?

**Comment by 123Venom** [comment] 2019-09-19 02:28
directory listitems do not allow font size changes sadly.  Would have to be converted to a window list, which yields a ton more control.  Honestly that was my original plan and why I did not put allot of time into the original release of multiline.  I changed my logic because my to-do list is growing faster than I can tackle it so this is prob going to stay directory list type for awhile yet.

**Comment by diemenz** [comment] 2019-09-19 02:34
Fair enough. Thanks again for a great add on! I think you do more updates then anyone else out there and it’s appreciated.

**Comment by 123Venom** [comment] 2019-09-19 02:41
use to push one out every 3 days but times been short lately and works busy as hell.  I fixed a couple small things to..damn I need to start writing it down vs. when changelog time comes trying to remember.  Trakt watch list was not updating immediately if you added a title...I had an old cache value I messed with saved and noticed it so that it's cured.  Ohh and since I was working on multiline once again someone asked for color options to the progress dialog when scrape begins.  So the red/green you see now you can change.
