### ISSUE TITLE
Trakt Progress: Recently Aired vs. Recently Watched

### ISSUE THREAD

**Issue by bigpoppapaul** [123Venom/plugin.video.venom#2] opened 2019-06-22 01:57 UTC
Is there a way to bring this option back. It's in almost all the Exodus forks but seems to have been removed from Venom. 
Thanks for a great addon, regardless.

**Comment by 123Venom** [comment] 2019-06-22 22:56
boy that was so long ago I made changes to this..taking a shot in the dark I seem to recall doing it because it was the same elsewhere.  Isn't your Trakt history a list of all your recently watched?  Isn't "New Episodes" a list of recently aired?  I'd have to dig back into this but off the top of my head, and not not able to review at this moment, that's what I'm recalling that it was duplicate cases elsewhere and the goal I had was to clean up a few.  I'll compare redux later and see if that's correct or not but there was a reason I did this.

**Comment by bigpoppapaul** [comment] 2019-06-26 13:35
Sorry, no, that's not what I was referring to. It's simply an option that shows your Trakt Progress of tv shows in the order of your choosing between the two options. It'll either list the episodes in the order of whatever shows you watched most recently, or it will list the episodes in order of what has most recently aired. It's not a big deal, but I always put it to "recently aired" that way I always see the newly aired episodes on top.

**Comment by 123Venom** [comment] 2019-06-27 00:57
so it's sorting options for Trakt Progress you want?  Check settings as I did add sorting options that should cover what you're looking for.  I set this to "Date Watched" so it lists the next episode based on when watched date/order.  If you set "New Episodes" to "Trakt Progress" I believe that will list them by aired date but not confirmed.

**Comment by bigpoppapaul** [comment] 2019-06-27 13:03
Ahhh, see I use Trakt Episodes as well so I didn't want to change that. However, I don't want to hassle you, it's just been an option in most Exodus forks and I thought it might be easy to bring it back. No biggie though, I'll make due with the way it is.

**Comment by pctech101** [comment] 2019-07-14 19:31
I am used to using Trakt Progress but it isn't populating a list. I can see history so I know trakt is functioning, but I want things sorted by my last watched/new episodes like the other dude

**Comment by 123Venom** [comment] 2019-07-17 04:17
I'm going to have a look at doing something for this issue for ya after I wrap up latest push.  I'm thinking to enhance my sorting functionality I added while back to include a "Date Aired" option to this list.

![Capture](https://user-images.githubusercontent.com/46383815/61346740-0eaeb680-a828-11e9-8394-1062587b9f46.PNG)

That sound good? Let me know your opinion and hopefully I can get that out before weeks end.

**Comment by 123Venom** [comment] 2019-07-17 04:45
Actually I had a quick look at this while I geared up for a change, bear with me as it's been months since I re-wrote that whole sorting.  Looking things over the "Date Premiered" option should be your "Recently Aired' request and "Date Watched" should be your "Recently Watched" request.  I test flipped those options and it seemed to me to be what you are after.  Check and let me know.

**Comment by pctech101** [comment] 2019-07-18 23:28
I removed my original post. I saw another thread that was closed.  It works on my home box but not my friends, until I reset kodi and added your repo again. It didn't want to work on my old setup. I needed to refresh. Thanks for all your efforts. Gods blessings.

**Comment by 123Venom** [comment] 2019-07-19 17:52
so are you good with the new sorting methods?  If so I'll close this.

**Comment by pctech101** [comment] 2019-07-19 19:36
Please, it works properly for me after a clean setup. Thanks for your efforts

**Comment by 123Venom** [comment] 2019-07-19 20:52
ok good to know so I'll close this issue.

**Closed** 2019-07-19 20:52 UTC

**Comment by bigpoppapaul** [comment] 2019-08-11 06:10
Hey 123Venom, the person that replied wasn't me, I was the one that started this issue. I just wanted to say, the sorting methods you set up for Trakt Progress were exactly what I was looking for. Thank you.

**Comment by 123Venom** [comment] 2019-08-12 03:12
lol..I had a thought that's what you needed was a separate sort method for Progress.  Test something for me of a recent discovery with a Trakt api bug that got past me.  The Trakt api defaults to 10 list items in the response...however if you set your "Page Item Limit" to 20 Trakt gives you the first 10 in the expected order but the next 10 are random items all over the damn place.  I use a "Page Item Limit" of 10 myself so this got by me during testing.  This came up last night and I've not had a chance to look at it yet.  If it's true I have a couple thoughts on a cure.  The best solution is to hard code the problem ones to 10 list items and be done with it.
