### ISSUE TITLE
TV Show scraping gone down?

### ISSUE THREAD

**Issue by JaxJoe01** [123Venom/plugin.video.venom#76] opened 2020-09-06 20:17 UTC
Last couple of updates in the past week, anyone noticing shows not scraping?  I have to goto another addon which I do not prefer to do at all.  I can find them online, I can find them in the other addons yet venom still doesn't find them even with RD.

**Comment by JaxJoe01** [comment] 2020-09-06 21:32
BTW still not sure if we use internal/open scrapers or all open.  Just stating TV scraping is horrible while movies are just fine.

**Comment by ShaVerZ** [comment] 2020-09-07 01:14
Similar issue here, it shows sources being found whilst scraping but when it comes to display them an error is displayed.

Arctic Horizon Skin

Kodi Log: https://pastebin.pl/view/5d6a1b26

**Comment by ShaVerZ** [comment] 2020-09-07 01:14
> Last couple of updates in the past week, anyone noticing shows not scraping? I have to goto another addon which I do not prefer to do at all. I can find them online, I can find them in the other addons yet venom still doesn't find them even with RD.

Similar issue here, it shows sources being found whilst scraping but when it comes to display them an error is displayed.

Arctic Horizon Skin

Kodi Log: https://pastebin.pl/view/5d6a1b26

**Comment by bjbca** [comment] 2020-09-07 02:27
have you tried clear ALL cache

**Comment by ShaVerZ** [comment] 2020-09-07 03:52
> have you tried clear ALL cache

The single, most important thing i should try but I always forget it! Ggrrgghh! Seems to have fixed the issue, thanks for the helpful reminder 👍

**Comment by JaxJoe01** [comment] 2020-09-07 04:16
Sorry, will try that.  I auto clear all my cache when I open but will try it manual way.  My problem was certain shows were not coming up with any for SD - 1080 but another addon worked without issue.  I don't use skins or any other sideloads for anything.  Venom is perfect the way it is.

**Comment by JaxJoe01** [comment] 2020-09-07 05:04
Yeah, definitely not it.  bigbrother streetoutlaws memphis and a couple from trutv do not work.  Work fine on another addon not using open scrapers.  Was just trying to get a feeler out if it is internal or open scrapers.  Tried looking for how to test scrapers and couldn't find a reasonable walkthrough to troubleshoot / test them. If anyone has one, please feel free to post links or message me directly.  Would like to help out any way I can.  Still like Venom for all it has and does compared to the rest... As well as the speed in which it works compared to others.  To the creator / dev / whomever.  Thank YOU!

**Comment by 123Venom** [comment] 2020-09-07 14:43
This suppose to be one title or 3?  `bigbrother streetoutlaws memphis` as you typed it.  No comma, no spaces where I'm guessing there suspect be.  Please correct the title, or titles.
Are you using free hosters?  you on v4.1.2?
I did one search as a guess for `Big Brother` and  search result pulled up one cached torrent from Bitlord for seasons 1 thru 14 as a pack file.  Not a very popular show it would seem.  If you're on free hosters prob nothing.  I'm also in the process of pulling free hoster support, I'm all done with them.  It will be gone within a month. resolveURL dependency will also be removed.

**Comment by JaxJoe01** [comment] 2020-09-07 15:59
2 titles... some people don't like names ... it is whatever.  And the recent shows.  As I said initially, I always use RD, never had a need to use anything else.  If something other than RD works better, I'll switch to it immediately.

Never use free except many a year ago.

big brother... street outlaws memphis...latest show  For the past what.... 6-8 years, shows get released / uploaded within the hour of the show/movie being released.  Just noticing shows (movies have always been fine) slinking down to not being available an hour after and sometimes 2 weeks after using venom.  Other addon it pulls and plays or if on my pc, I can pull up many a stream tv show site and watch any of them.

**Comment by 123Venom** [comment] 2020-09-07 23:20
I did a test on your `Street Outlaws Memphis` show

S01E01.
Seren pulled in 1 cached torrent
Venom pulled in 1 cached torrent
The Crew pulled in 3 cached torrents but 2 looked suspiciously like duplicates. 

S04E01, to broaden a range of years.
Seren pulled in 2 cached torrents
Venom pulled in 4 cached torrents.
The Crew pulled in 3 cached torrents.

Nothing is jumping out at me like a problem or difference between 3 addons I just tested.  Maybe post some screenshots of what you're seeing so I can compare.

**Comment by dvoigt** [comment] 2020-09-08 18:16
I think I was having the same issues with any show OR film I tried, it appeared  immediately with the latest Venom version and disappeared immediately when reverting back to the previous. Sources are being scanned, and then next step where you select a source to play, empty screen. I'm NOT using torrents, though, only streaming pages.

**Comment by JaxJoe01** [comment] 2020-09-09 00:30
It was all the latest episodes.  Not sure about previous seasons.  Reason why I was asking if it was internal venom or all external open scrapers.  TV shows - completely depends.  Movies, all working as 20+ scrapes.  TV Shows, either 5 or less, a bunch load as normal for completely mainstream shows or 0 shows for the shows I mentioned for days or a week past most recent episode.  If it is openscraper issue, will find their channel and post.

**Comment by 123Venom** [comment] 2020-09-09 03:45
> 
> 
> I think I was having the same issues with any show OR film I tried, it appeared immediately with the latest Venom version and disappeared immediately when reverting back to the previous. Sources are being scanned, and then next step where you select a source to play, empty screen. I'm NOT using torrents, though, only streaming pages.

If you were on free hosters only then yes previous version had a goof with a new feature I added for uncached torrents and neglected to even consider free hosters so it was broken for those sources, it's fixed.  Bad news for you though....next version of Venom some massive changes coming and free hoster support is being completely removed.  Sorry to tell you I just got increasingly annoyed with them and do not ever use them myself so felt it was time they die.  Many of the streaming sitres have been going behind Cloudflare v2 challenge for months now and I believe OpenScrapers free hoster count has already been cut by 60% of them due to this and still going.  FEN is also in the process of removing support so you might have to seek a new option.  There's still plenty of good addons supporting them.  We're removing free hosters from OpenScrapers as well.

**Comment by 123Venom** [comment] 2020-09-09 04:02
> 
> 
> It was all the latest episodes. Not sure about previous seasons. Reason why I was asking if it was internal venom or all external open scrapers. TV shows - completely depends. Movies, all working as 20+ scrapes. TV Shows, either 5 or less, a bunch load as normal for completely mainstream shows or 0 shows for the shows I mentioned for days or a week past most recent episode. If it is openscraper issue, will find their channel and post.

I just checked S04E24 and S04E25 of `Street Outlaws Memphis` and neither Seren, Venom, or The Crew managed to pull in one single cached torrent for these latest last two aired episodes.  Sure looks to me like the problem is nobody has uploaded them, or if so they're just not cached links available.  What's the addon that is pulling in links when these three I just tested do not? Even during the scrape process the dialog you see in Venom will count raw links returned (unchecked for cached, or any filtering you enable).  That dialog is not showing me anything at all in Venom, or The Crew either.  I just do not think there's anything out there.  If there is show me a screen shot of the site you did stream and watch from.  If you do a manual search at any torrent site for these episodes that's what I want to see and then I can track why nothing is pulled in.

I'm not sure what your asking about internal or external?  All scraper files are part of OpenScrapers, which I'm the dev who maintains those! So don't bother asking over there you'll just get me again..lol

**Comment by dvoigt** [comment] 2020-09-09 06:50
Thanks for the warning. Without free hosters, Venom and OpenScrapers will be completely useless to me. Thanks for the software, though, I appreciate all the work you've been putting in.

**Comment by 123Venom** [comment] 2020-09-09 07:42
> 
> 
> Thanks for the warning. Without free hosters, Venom and OpenScrapers will be completely useless to me. Thanks for the software, though, I appreciate all the work you've been putting in.

Sorry man...it's coming whether we like it or not.  Cloudflare v2 has been killing us with loosing streaming site so frankly it's only a matter of time.  I really do suggest a premium account.  You can of course disable auto updates in Venom and OpenScrapers so you can stay using it with free hoster support.

**Comment by dvoigt** [comment] 2020-09-09 10:35
Will do that, thanks!

**Comment by 123Venom** [comment] 2020-09-13 02:44
Well @JaxJoe01 I've waited 4days for the info and seem it's not coming so I'm closing this as it seems to be a non issue when tested in 3 addons producing the same results

**Closed by 123Venom** 2020-09-13 02:44 UTC
