### ISSUE TITLE
Trakt progress not populating

### ISSUE THREAD

**Issue by Liquidrag** [123Venom/plugin.video.venom#1] opened 2019-06-16 14:52 UTC
Trakt episode progress is blank.

**Comment by drinfernoo** [comment] 2019-06-16 17:43
You have to authorize Trakt first.

**Comment by 123Venom** [comment] 2019-06-19 16:09
if Trakt not authorized that menu choice will not even show up proceeding this check "if traktCredentials is True".  

I can't reproduce it myself so I suggest clearing out cache across the board, including using AfterMath for system cache.

**Comment by rrosajp** [comment] 2019-06-19 21:46
hi 
i had same problem and i did clean all cache kodi as well as  addon cache but still no result.but all other menu from Trakt work fine but not progress showing. btw its great addon i appreciate yr hard work thanks to add UpNext integration.

**Comment by Liquidrag** [comment] 2019-06-19 22:06
Same as @rrosajp, Auth trakt and everything populates except progress. This is on a fresh install.

**Comment by drinfernoo** [comment] 2019-06-20 00:27
Working fine for me here.

**Comment by 123Venom** [comment] 2019-06-20 01:17
Since two of you are having this issue here's what I propose.  I'm going to create a dev branch and add a new version there where I add a shit load of logging to see if I can capture what's happening each step of the way. Prob some title with either a goofy character or missing data that generates a key error but that even should show up in the log if that's the case.  Nothing in the log?  Should see a GetDirectory error since the list is empty...let me know on that.  I'll try to tackle this added logging tonight or tomorrow.

**Comment by 123Venom** [comment] 2019-06-20 01:19
> 
> 
> Working fine for me here.

ya same here and it makes it tough when you can't duplicate the issue but some good old fashioned extra logging should tell me something.

**Comment by 123Venom** [comment] 2019-06-20 02:26
I uploaded a version 2.9.6a to the zips/plugin.video.venom dev branch.  Install that as it has extra logging so I can try and track this beast.  Make sure you use "Enable Debug" in settings and set the "Debug Log" to "Addon Log" so I can just scroll through my own logging and not mixed with kodi log info.

**Comment by rrosajp** [comment] 2019-06-20 12:36
thanks for looking in to the issue
i have done as u suggested and hear is the log [https://pastebin.com/wRP9GKDv](url)
btw it scarp the list but not displaying

**Comment by 123Venom** [comment] 2019-06-20 17:49
That helped but not nailed it yet.  The Trakt api response looks good and I didn't find any breaks in the list items...however I only see 10 items per below.  Can you confirm these items for me.
![Capture](https://user-images.githubusercontent.com/46383815/59869375-2ac25380-9361-11e9-8ccb-d0b1d495c3bd.PNG)
If that count is right then this helps narrow it down and I may have to do one more dev release to caption the final function.  If that count is in fact wrong/short then that complicates it because a title is breaking it and we'd have to find it.

**Comment by rrosajp** [comment] 2019-06-20 18:06
yeah it's 10 items on progress.

**Comment by 123Venom** [comment] 2019-06-20 18:22
I just tried something else.  I have 56 items in my Trakt "Progress" so I compared my log vs. yours to see if I can see anything I missed in my first look...there is!  One of the functions before the list items are populated for you is about a 20+ items it gathers from tvdb...director, cast, blah blah, all after it gets your trakt list.  I added a log entry for that final step and my 56 items has that log entry while yours does not.

![Capture](https://user-images.githubusercontent.com/46383815/59871636-0a48c800-9366-11e9-94a0-2556d9d8d12f.PNG)

Now I believe I know where it's broken.  I'll have to add a log entry for each attempt it collects those variables you see "values = " from TVDb.  As I suspected all indications says one of those titles has some funky character I may not be accounting for.  I should find it and thanks for your patience.

**Comment by 123Venom** [comment] 2019-06-20 19:03
> 
> 
> yeah it's 10 items on progress. there is no title breaking as per i know. btw is that 'unaired': '' in
> line 165 of episodes.py self.list sorted list causing that? but in same dict its have 'premiered': '2019-04-30' n also i make sure in setting enable the option "showunaired" so it should not filter out.

when you looked at that dict key for unaired did you see a condition with a value?  That variable is used as a flag and if the key value is "" that is None type or False...ignore that please.  If you saw....

'unaired': 'True' and a past date in year, or premiered,  I'd have a concern.

**Comment by 123Venom** [comment] 2019-06-20 21:36
I just saw an issue brought up about Seren in a similar case where episodes were not showing up and the list was empty.  It was discovered that TVDb uses a different naming scheme for some shows seasons list....like Season 1 vs. Season 2010...why the heck they do different format is really not wise imo but I wonder if that's the case here so I'm heading to TMDb to do a show look up on your 10 item list to see if that's what's doing this.  If that is the condition I'll have to add a check for this format difference and see how this is then carried throughout so this could be a bit involved if this is a format change TVDb is doing.

**Comment by 123Venom** [comment] 2019-06-20 22:50
Damn this is really baffling.  None of your 10 items does TMDb use a different Season format so we can rule that out.  I then went through and added each of your shows to my Progress one by one...went through all 10 and it still works.  I'm stumped!

![Capture](https://user-images.githubusercontent.com/46383815/59885902-e055cc80-938a-11e9-9e53-092bf12287bc.PNG)

I'm going to upload another version to the dev branch in a bit as I added more logging to capture what might be happening with the TMDb api.  Just because I verified at TMDb's site that there's no strange format issue of Season # doesn't mean it's not in the api different so we can test that.

And just so you know, this is not a skin issue but I do use Silvo as well.

**Comment by rrosajp** [comment] 2019-06-21 00:10
sorry i just got home need to run some errand .thanks for all u does,btw i know silvo is more versatile in all respect. i still think it's in making episode directory  something causing Not to display list.or may b i m wrong.

**Comment by 123Venom** [comment] 2019-06-21 00:34
the line #956 I told you that is not in your log, but is in mine, say it's the TVDb api response failing on a title for some reason that is not happening to me on the same exact titles of yours that I added.  Think I inadvertently kept saying TMDb, it's TVDb in use here.  The list has to be built to populate the directory and if it errors the whole thing takes a dump so you have to follow it start to finish, no errors.  I can intentionally cause a Unicode error on one item and make it do this.

Shot in the dark but have you checked your takt online account against that 10 item list?  I'm wondering if there's some sort of corruption somewhere.  With only 10 items if it were me I'd first run that new dev, with the added TMDb logging I added...if that doesn't tell me what the issue is I'd start removing items from my tarkt progress online till I found it.

**Comment by rrosajp** [comment] 2019-06-21 01:04
i did run new dev  i still not getting line #956
here is log
https://pastebin.com/fxnr4dVE

**Comment by rrosajp** [comment] 2019-06-21 01:16
sorry got to go c u tomorrow. we will start with fresh mind set .

**Comment by 123Venom** [comment] 2019-06-21 07:26
![Capture](https://user-images.githubusercontent.com/46383815/59904395-6268e400-93d1-11e9-927f-c38c250db31a.PNG)
![Capture1](https://user-images.githubusercontent.com/46383815/59904399-66950180-93d1-11e9-8ecb-d9c594b860b0.PNG)

I realize you want to watch shows but your list changed and that complicates things.  What happened to "Berlin Station"?..did you remove that via "Unwatched" or online account?  Your still showing 10 items but the item counter I added says 9 so something is getting all messed up now with trakt.  I felt like I was looking at TVDb as the culprit, which it still is, but your changes now complicates this as the list no longer matches from trakt either.  With no api response from TVDb I can add some logging so I can see what it is the response header....you sure got one strange issue I've never seen before. I still know for a fact you have some TVDb api problem as you have no response in the log and not one single entry shows up beyond line 637 and I added a ton of logging after that point.

**Comment by 123Venom** [comment] 2019-06-21 07:41
![Capture2](https://user-images.githubusercontent.com/46383815/59905588-a01b3c00-93d4-11e9-9031-eb4dc5e1f422.PNG)
![Capture4](https://user-images.githubusercontent.com/46383815/59905592-a1e4ff80-93d4-11e9-80ab-516c435f7651.PNG)

You're not even getting logging of the simple url used for TVDb...might fail if TVDb id is not passed but according to your dict it's in there in that second snapshot.

What hardware?
What Kodi version?

I'm getting a returned url
![Capture5](https://user-images.githubusercontent.com/46383815/59906299-63504480-93d6-11e9-94ba-d5b9336c42f6.PNG)

**Comment by rrosajp** [comment] 2019-06-21 11:02
hi gm
had guest so btw not watchin tv! anyway.
What hardware? : win 7
What Kodi version? : 18.1
i checked on site there is all 10 show which was previously "Berlin Station" is still there
i have uninstall n reinstall venom here is new log file 
[venom.log](https://github.com/123Venom/plugin.video.venom/files/3314145/venom.log)

**Comment by rrosajp** [comment] 2019-06-21 11:53
if it help .
in calendar menu option 
def trakt_episodes_list(self, url, user, lang): work as u know its have more or less same func def items_list(i): 
to create isFolder = False
and showing the list .

but in progress menu option
def trakt_progress_list(self, url, user, lang):
 not working since it create isFolder = True
both func create and populate list in def episodeDirectory(self, items):
before
control.addItem(handle=syshandle, url=url, listitem=item, isFolder=isFolder) @ line 1826
but not displaying.

**Comment by 123Venom** [comment] 2019-06-21 17:06
ya NOW it's getting TVDb api responses and Berlin Station is back.  I suspect your re-install did cure a portion of this problem, that is evident, and I'll review the items more closely tonight to see if all items are populated now.

**Comment by Hammerggf** [comment] 2019-06-22 04:17
@123Venom i too am experiencing these issue. Is there anything i can do to help discover the issue? im a novice when it comes to playing with logs and stuff so id need a quick bullet point of what you need from me.

**Comment by 123Venom** [comment] 2019-06-22 23:06
No there's nothing you can do to assist.  Lately I'm getting hammered in emails and posts in a few places so I just need the time, and things to cool down, to get back into the most recent log that was posted and examine it.

**Comment by 123Venom** [comment] 2019-06-23 00:17
@rrosajp I reviewed the latest log and all values seems to be there and we look good up to the point of building the directory list items.  I'm adding some logging to see what's going on there and where it's breaking.

In the mean time I spotted a check I added some time ago in that "episodeDirectory" function that builds the list you should be seeing.

This notification is not in your typical exo fork.  Do you get a notification per what I added in red?
![notice](https://user-images.githubusercontent.com/46383815/59970024-3319ba80-952a-11e9-9218-ab8447f6e81a.PNG)

I'll let you know when I get another dev build to test, prob later tonight.  Also can check for errors in you kodi log because I already had added some traceback import cases to log additional errors that might be reported there, or just upload it and I'll review it.

**Comment by 123Venom** [comment] 2019-06-23 06:11
@rrosajp I uploaded a new dev version for you to test.  I've added logging to the final step as well as some traceback so fingers crossed it captures it because that is the last function left.

**Comment by 123Venom** [comment] 2019-06-23 08:54
If I caught you in time can you check your side panel option and see what it's set at.  If slipped to "Unwatched" my list goes empty.  I always use "All" and leave it there as that is generally a skin default but it was just brought to my attention that side panel option is working backward so I thought perhaps this might be your issue.
![Capture](https://user-images.githubusercontent.com/46383815/59973851-c676de00-9572-11e9-8c40-3406cac9d1d2.PNG)
My list emptied when I flipped it to that.  Check it and let me know because you're last log seemed right...except we were going to test the final function in the file as a last resort.  My hope is this side panel is it!

**Comment by Hammerggf** [comment] 2019-06-23 09:06
> If I caught you in time can you check your side panel option and see what it's set at. If slipped to "Unwatched" my list goes empty. I always use "All" and leave it there as that is generally a skin default but it was just brought to my attention that side panel option is working backward so I thought perhaps this might be your issue.
> ![Capture](https://user-images.githubusercontent.com/46383815/59973851-c676de00-9572-11e9-8c40-3406cac9d1d2.PNG)
> My list emptied when I flipped it to that. Check it and let me know because you're last log seemed right...except we were going to test the final function in the file as a last resort. My hope is this side panel is it!

Just tried this and you are correct my Hide watched feature is working in opposite for Venom!

**Comment by 123Venom** [comment] 2019-06-23 09:12
Does the same thing in Gaia also.  Prob moving this up in priority to fix.  Hopefully this week I can get it done.

**Comment by rrosajp** [comment] 2019-06-23 11:37
@123Venom 
yee it the skin option doing that. now it display the list.
thanks a lots

**Comment by Hammerggf** [comment] 2019-06-23 12:12
> Does the same thing in Gaia also. Prob moving this up in priority to fix. Hopefully this week I can get it done.

Mate don't stress too much! its not addon breaking its just a post saying how to counter it for now and get to it in your own time!

**Comment by rrosajp** [comment] 2019-06-23 14:58
@123Venom 
here is the log_util.py if u like to use.
https://gist.github.com/rrosajp/ebaf2b097ecb2f7770e16433bb3e67d6

when u like to debug
insted of this
log_utils.log('from line 274 of episodes.py self.blist = %s' % str(self.blist), log_utils.LOGDEBUG)

use this:
log_utils.log('self.blist =  %s' % self.blist, __name__, log_utils.LOGDEBUG)
so u don't have to change line # in each line. 

it will give to log like this:
[2019-06-23 10:44:46] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.menus.episodes.calendar() Line # :276
                       msg : self.blist =  [{'rating': '8.0', 'tmdb': '66282', 'imdb': 'tt5191110', 'year': '2016', 'duration': '60'.................

**Comment by 123Venom** [comment] 2019-06-23 18:51
@rrosajp 
Are you using a different log_utils.py than I have because the log function does not take 3 args in your example, version I have takes 2 and will error on passing a 3rd or using your line.

log_utils.log('self.blist = %s' % self.blist , name , log_utils.LOGDEBUG)

**Comment by 123Venom** [comment] 2019-06-23 18:53
> 
> 
> > Does the same thing in Gaia also. Prob moving this up in priority to fix. Hopefully this week I can get it done.
> 
> Mate don't stress too much! its not addon breaking its just a post saying how to counter it for now and get to it in your own time!

Not stressing at all.  Just felt it's import this be fixed ahead of other matters I'm working on, that all.

**Comment by 123Venom** [comment] 2019-06-24 03:41
I have the fix and testing it now but all seems good.  Depreciated infoLabel I was not aware of.  Seems some skins are ok with the old value used in some menus but it definitely does not like it in Trakt Progress.  You can also see it while you're in Trakt Progress by bringing up "Information", depending on skin, and you'll see something like "playcount: 2019"...ya a little wrong there and that was the key for me to track what's wrong with it.

**Comment by rrosajp** [comment] 2019-06-24 10:32
@123Venom 
it's same as yours i just did lit mod on yours.
@ line3
import os, time, cProfile, StringIO, pstats, json, xbmc,inspect
as:@ line 15
def log(msg,caller=None, level = LOGNOTICE):
insted  of
def log(msg,level = LOGNOTICE):

and added @ line 23
if caller is not None and level == LOGDEBUG:
            func = inspect.currentframe().f_back.f_code
            line_number = inspect.currentframe().f_back.f_lineno
            caller = "%s.%s()" % (caller, func.co_name)
            msg = 'From func name: %s Line # :%s\n                       msg : %s'%(caller,line_number,msg)

u can find in gist link i attached:
https://gist.github.com/rrosajp/ebaf2b097ecb2f7770e16433bb3e67d6

**Comment by stathis95194** [comment] 2019-06-24 14:45
My watched/unwatched issue on trakt progress is fixed with the latest update. Thanks a lot!!

**Comment by 123Venom** [comment] 2019-06-24 14:57
@rrosajp I'll give that mod a whirl little later.  Looks VERY promising to save me some time logging, and I do a ton of it to back check myself.  Appreciate it.

@stathis95194 no problem.  Was an easy fix...old infoLabel was used and skin was freaking out on it but only effected Progress, and one other Trakt list I spotted it mucked with.

**Comment by 123Venom** [comment] 2019-06-24 15:36
@rrosajp works GREAT!!! and thank you.  You still had another typo though.  no white space  __name__...I spotted the white space right before "name" and dunder.

Closing this as the issue is also now fixed.

**Closed** 2019-06-24 15:37 UTC
