### ISSUE TITLE
Posters/art broken if changing api language 

### ISSUE THREAD

**Issue by Tinuz97** [123Venom/plugin.video.venom#7] opened 2019-07-10 05:53 UTC
Hi, i hope I can explain it in English.
If I change the api language to Dutch (the movie information in Dutch language) all the posters from movies are gone (I see all venom posters from the addon), if I switch it back to English, posters etc working again.

It does not break every section, but as a example, it does break trending (trakt) section (so you have one to replicate the issue). 

Thx.

**Comment by Tinuz97** [comment] 2019-07-10 05:57
Did check it again, it does break everything that is related to trakt menu's, tmdb and imdb sections do work if dutch is enabled.

**Comment by 123Venom** [comment] 2019-07-10 07:19
I'll look at it but might be a day or so..had a long ass day helping friends and family and took the day off from work to do so and now behind.  I'll check it out just please be patient as I'm a bit overloaded at the moment.

**Comment by Tinuz97** [comment] 2019-07-10 07:23
No need to hurry m8.
I just leave it on English for now, take your time :)

**Comment by 123Venom** [comment] 2019-07-10 07:33
as much as I'm literally half asleep right now and full of grease. I had a look anyway out of curiosity.  I set api lang to Dutch and all movie categories produced artwork, even the the trakt lists.  Where are you seeing this failure?  Posting a log does help me to review it

**Comment by Tinuz97** [comment] 2019-07-10 07:51
Do I need to enable something extra for detailed log, of can I find it in the regular kodi log?
Maybey kodi Interface has something to do with it, mine is set on dutch also. 
I am going to check if kodi's interface language does something, and check log. Be back asap. 

I have the issue only with all trakt sections (missing posters)

**Comment by Tinuz97** [comment] 2019-07-10 08:00
This error at recommended, now i am gonna search for the art in the log. But i noticed this one also.


2019-07-10 09:58:51.604 T:9640   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-07-10 09:58:51.605 T:9640   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.venom/?action=movies&url=traktrecommendations) failed
2019-07-10 09:58:51.605 T:9640   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.venom/?action=movieNavigator)
2019-07-10 09:58:51.605 T:9640   DEBUG:   ParentPath = [plugin://plugin.video.venom/]
2019-07-10 09:58:51.605 T:9640   DEBUG: Loading items: 26, directory: plugin://plugin.video.venom/?action=movieNavigator sort method: 0, ascending: false
2019-07-10 09:58:51.618 T:1248   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.venom] took 13 ms
2019-07-10 09:58:51.621 T:10852   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-07-10 09:58:51.631 T:10852   DEBUG: Thread BackgroundLoader 10852 terminating
2019-07-10 09:58:53.721 T:9640   DEBUG: Keyboard: scancode: 0x5b, sym: 0x0137, unicode: 0x0000, modifier: 0x10
2019-07-10 09:58:53.721 T:9640   DEBUG: CInputManager::HandleKey: win-leftwindows (0x10f0d6) pressed, action is
2019-07-10 09:58:53.850 T:9640   DEBUG: Keyboard: scancode: 0x5b, sym: 0x0137, unicode: 0x0000, modifier: 0x0
2019-07-10 09:58:55.988 T:9640   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-10 09:58:56.272 T:9640   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

**Comment by Tinuz97** [comment] 2019-07-10 08:03
I think this one is for the missing posters (trak sections, api language dutch, kodi interace also dutch), if i set it back to english (api venom) the error is gone. 
But here is a log:


2019-07-10 09:59:44.555 T:9640   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-10 09:59:44.624 T:1420   DEBUG: Thread JobWorker start, auto delete: true
2019-07-10 09:59:45.209 T:1420   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/47f6aec5.png
2019-07-10 09:59:45.213 T:1420   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\boxsets.png' to '4/47f6aec5.png':
2019-07-10 09:59:45.213 T:1420   DEBUG: cached image 'special://masterprofile/Thumbnails/4/47f6aec5.png' size 512x512
2019-07-10 09:59:45.238 T:5712   DEBUG: Thread JobWorker start, auto delete: true
2019-07-10 09:59:45.273 T:5712   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/2/253b4073.png
2019-07-10 09:59:45.277 T:5712   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\oscar-winners.png' to '2/253b4073.png':
2019-07-10 09:59:45.277 T:5712   DEBUG: cached image 'special://masterprofile/Thumbnails/2/253b4073.png' size 512x512
2019-07-10 09:59:45.288 T:1420   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0ed4ca34.png
2019-07-10 09:59:45.292 T:1420   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\languages.png' to '0/0ed4ca34.png':
2019-07-10 09:59:45.292 T:1420   DEBUG: cached image 'special://masterprofile/Thumbnails/0/0ed4ca34.png' size 512x512
2019-07-10 09:59:45.304 T:9488   DEBUG: Thread JobWorker start, auto delete: true
2019-07-10 09:59:45.333 T:9488   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/d/d4ff1350.png
2019-07-10 09:59:45.337 T:9488   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\people.png' to 'd/d4ff1350.png':
2019-07-10 09:59:45.337 T:9488   DEBUG: cached image 'special://masterprofile/Thumbnails/d/d4ff1350.png' size 512x512
2019-07-10 09:59:45.354 T:952   DEBUG: Thread JobWorker start, auto delete: true
2019-07-10 09:59:45.375 T:5712   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/c/c5ce46da.png
2019-07-10 09:59:45.381 T:5712   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\years.png' to 'c/c5ce46da.png':
2019-07-10 09:59:45.381 T:5712   DEBUG: cached image 'special://masterprofile/Thumbnails/c/c5ce46da.png' size 512x512
2019-07-10 09:59:45.420 T:952   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/431697b1.png
2019-07-10 09:59:45.424 T:952   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\genres.png' to '4/431697b1.png':
2019-07-10 09:59:45.424 T:952   DEBUG: cached image 'special://masterprofile/Thumbnails/4/431697b1.png' size 512x512
2019-07-10 09:59:48.237 T:9640   DEBUG: Keyboard: scancode: 0x5b, sym: 0x0137, unicode: 0x0000, modifier: 0x10
2019-07-10 09:59:48.237 T:9640   DEBUG: CInputManager::HandleKey: win-leftwindows (0x10f0d6) pressed, action is
2019-07-10 09:59:48.238 T:9640   DEBUG: ------ Window Deinit (Pointer.xml) ------
2019-07-10 09:59:48.334 T:9640   DEBUG: Keyboard: scancode: 0x5b, sym: 0x0137, unicode: 0x0000, modifier: 0x0
2019-07-10 09:59:48.404 T:9640   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-10 09:59:53.545 T:9640   DEBUG: ------ Window Deinit (Pointer.xml) ------
2019-07-10 10:00:15.506 T:1420   DEBUG: Thread JobWorker 1420 terminating (autodelete)
2019-07-10 10:00:15.506 T:9488   DEBUG: Thread JobWorker 9488 terminating (autodelete)
2019-07-10 10:00:15.507 T:952   DEBUG: Thread JobWorker 952 terminating (autodelete)
2019-07-10 10:00:15.512 T:5712   DEBUG: Thread JobWorker 5712 terminating (autodelete)
2019-07-10 10:01:31.037 T:10716   DEBUG: Thread JobWorker start, auto delete: true
2019-07-10 10:01:31.037 T:9640   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-10 10:01:31.187 T:10716   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/a/afb04878.png
2019-07-10 10:01:31.192 T:10716   DEBUG: Caching image 'C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.venom\resources\artwork\venom\certificates.png' to 'a/afb04878.png':
2019-07-10 10:01:31.192 T:10716   DEBUG: cached image 'special://masterprofile/Thumbnails/a/afb04878.png' size 512x512
2019-07-10 10:01:31.220 T:6264   DEBUG: Thread JobWorker start, auto delete: true

**Comment by Tinuz97** [comment] 2019-07-10 08:08
Yes ! i found a way to replicate the issue!.

Set the kodi interface to Dutch (nederlands) also, and you will get the issue.
If i set the Kodi interface to English (and leave the api on Dutch in venom) the art is working.
If i set Kodi interface also on Dutch,the art is missing again.

**Comment by Tinuz97** [comment] 2019-07-10 10:51
This one is failing also (dutch or english api,or kodi on english/dutch)
In theaters link (imdb).

2019-07-10 12:48:27.339 T:7068   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-07-10 12:48:27.339 T:7068   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.venom/?action=movies&url=theaters) failed
2019-07-10 12:48:27.339 T:7068   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.venom/?action=movieNavigator)
2019-07-10 12:48:27.339 T:7068   DEBUG:   ParentPath = [plugin://plugin.video.venom/]
2019-07-10 12:48:27.340 T:7068   DEBUG: Loading items: 26, directory: plugin://plugin.video.venom/?action=movieNavigator sort method: 0, ascending: false
2019-07-10 12:48:27.354 T:8060   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.venom] took 15 ms
2019-07-10 12:48:27.359 T:3800   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-07-10 12:48:27.363 T:3800   DEBUG: Thread BackgroundLoader 3800 terminating
2019-07-10 12:48:29.438 T:7068   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0x40
2019-07-10 12:48:29.438 T:7068   DEBUG: CInputManager::HandleKey: ctrl-leftctrl (0x1f0d0) pressed, action is
2019-07-10 12:48:29.693 T:7068   DEBUG: Keyboard: scancode: 0x2a, sym: 0x0130, unicode: 0x0000, modifier: 0x41
2019-07-10 12:48:29.693 T:7068   DEBUG: CInputManager::HandleKey: ctrl-shift-leftshift (0x3f0d2) pressed, action is
2019-07-10 12:48:29.863 T:7068   DEBUG: Keyboard: scancode: 0x2a, sym: 0x0130, unicode: 0x0000, modifier: 0x40
2019-07-10 12:48:30.379 T:7068   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0x0
2019-07-10 12:48:30.631 T:7068   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0x40
2019-07-10 12:48:30.631 T:7068   DEBUG: CInputManager::HandleKey: ctrl-leftctrl (0x1f0d0) pressed, action is
2019-07-10 12:48:30.755 T:7068   DEBUG: Keyboard: scancode: 0x2a, sym: 0x0130, unicode: 0x0000, modifier: 0x41
2019-07-10 12:48:30.755 T:7068   DEBUG: CInputManager::HandleKey: ctrl-shift-leftshift (0x3f0d2) pressed, action is
2019-07-10 12:48:31.038 T:7068   DEBUG: Keyboard: scancode: 0x20, sym: 0x0064, unicode: 0x0004, modifier: 0x41
2019-07-10 12:48:31.038 T:7068   DEBUG: CInputManager::HandleKey: ctrl-shift-d (0x3f044) pressed, action is ToggleDebug
2019-07-10 12:48:31.038 T:7068  NOTICE: Disabled debug logging due to GUI setting. Level 0.
2019-07-10 12:48:31.038 T:7068  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
2019-07-10 12:48:31.038 T:7068  NOTICE: Disabled debug logging due to GUI setting. Level 0.
2019-07-10 12:48:31.038 T:7068  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
2019-07-10 12:48:32.468 T:7068  NOTICE: Stopping player
2019-07-10 12:48:32.468 T:7068  NOTICE: Storing total System Uptime
2019-07-10 12:48:32.468 T:7068  NOTICE: Saving settings
2019-07-10 12:48:32.480 T:7068  NOTICE: Saving skin settings
2019-07-10 12:48:32.488 T:7068  NOTICE: Stopping all
2019-07-10 12:48:32.488 T:7068  NOTICE: ES: Stopping event server
2019-07-10 12:48:32.802 T:10960  NOTICE: ES: UDP Event server stopped

**Comment by 123Venom** [comment] 2019-07-10 15:55
I'll look at this when I can but for now about all the time I have is to let you know that all those direct texture errros are not mine.  clean all the cache...use AfterMath to purge the Textrues13.db

**Comment by 123Venom** [comment] 2019-07-10 20:16
I tried changing languages as mentioned and still can not reproduce your issue, all artwork is there and I even flushed all cache with AfterMath and purged system db files...no problems here.  With the amount of textures errors you got this looks to me like a maintenance issue.

**Comment by Tinuz97** [comment] 2019-07-11 11:26
Weird, because I just installed kodi clean, just kod, nothing else.
Same issue with the posters if I do like I did write write earlier ( but no texture errors).

**Comment by Tinuz97** [comment] 2019-07-11 11:28
And with clean, realy clean.
Manually removed userdata folder (windows 10),and uninstalled kodi afterwards.

**Comment by 123Venom** [comment] 2019-07-12 00:25
I've tried to replicate on two different devices now and starting each from a complete cache wipe out...neither device reproduced your issue and all artwork was retrieved without issue from both TMDb & Fanart.tv.  Wipe out your cache with AfterMath and post your log.  I'll take one more stab at this but if nothing indicates this is addon related I'm not going to be able to help you with it.  A full debug log please!

**Comment by Tinuz97** [comment] 2019-07-14 01:49
3.0.5 fixed the issue for me, Dutch API language working, and art also.
Thx

**Comment by tmjvonboss** [comment] 2019-07-14 03:38
I'm starting to see a pattern here

Vague errors, no known causes -> next update instant fix

😂😂

**Comment by Tinuz97** [comment] 2019-07-14 08:22
Yeah weird, changed nothing (besides a clean kodi test setup, with only venom installed that I did write earlier, but also had the issue in this setup with 3.0.4)
3.0.5 did instantly fix the problem for me

**Comment by 123Venom** [comment] 2019-07-14 22:15
> 
> 
> I'm starting to see a pattern here
> 
> Vague errors, no known causes -> next update instant fix
> 
> joyjoy

What are you trying to say here?

**Comment by 123Venom** [comment] 2019-07-14 22:34
Look I think I'm getting your sarcastic comment so I'll spell it out for you because I will not tolerate ignorance when I come here and exhaust my free time to help you?, what nerve!  You think that was what a blow off treatment? I come here and type up all this shit to ditch you and blow smoke, trust me I got better things I can be doing with my free time.  An artwork problem came up on redditt/addons4kodi.  I investigated it...found the problem fixed it and THAT was the reason I pushed update 3.0.5.  So you two clowns tell me this...if over there I had no problems saying I found the problem and pushed a fix what you think I treated you unfairly and lie about finding the problem?  You don't believe me....here's the damn link for you. https://www.reddit.com/r/Addons4Kodi/comments/ccmuub/venom_movie_posters_missing_in_search_results/
If this just so happened to be related to your issue so be it and luck was on our side. And @tmjvonboss I spent a good deal of time trying to help you with "YOUR" communication problems at your hotel that had absolutely nothing to do with the addon and and this is the thanks I get, your sacrasm?  Good luck getting future responses from me, eitther of you.  Better yet I have the best solution for both of you.  Please uninstall my addon!  You don't deserve it.  May not be long before it's pulled and goes on a private server for my own use and development, and a select few who appreciate and treat people right will gain access but I assure you that won't be you two.  That comment was bullshit!!

**Comment by Tinuz97** [comment] 2019-07-14 22:45
Now I am confused.
I think these comments are not for me?
Because I was not sarcastic, i just wanted te report that it works great now, and my 2nd comment was for that other guy.

I just appreciate the work you do, and it is one of my favorites Addons. 
(ps, my native language is not English, so maybey that is why it is a little confusing for me, I did read clowns instead of clown).

**Comment by 123Venom** [comment] 2019-07-14 22:51
Then lets clear it up because I'll give the shit off my back to the right people but I do flip a switch on those undeserving of it and mistreat me in return and I'm very hot headed no doubt.  Here's what I look up and see. @tmjvonboss posts a sarcastic comment...the very next is yours and looks to me like you're agreeing with him..no?  That's what I came here and found and I flipped.  You may stand a chance I'll talk to pending your explanation and I buy it but @tmjvonboss is now a serious asshat imo and he WILL NOT EVER get another response from me.  I can't believe the hours I invested helping that guy for his isp block and that ain't my problem but I still tried to be helpful to him...lesson learned for me on his character that's for sure.

**Comment by Tinuz97** [comment] 2019-07-14 22:59
Sorry if it was like that I was agreeing to him, because I did not agree with that strange comment. 
The comment (from my intensions) was that I had no idea why it did work again, because I did not change anything (except that I did get the 3.0.5 update pushed).

Maybey the problem is that my main language is not English (I am a Dutch guy), and not used the proper English words, no idea.

But my intentions are always good, I hate drama or beeing sarcastic. 
I always try to help people in the scene if I can, that kind of guy I am.

**Comment by tmjvonboss** [comment] 2019-07-14 23:01
I am sorry, that is not the message I intended to convey

I really do appreciate what you are doing here and I did not mean to offend you
After reading my comment over a few times I can see how that was not the right thing to say, nor the right way of saying it

I meant to comment on the double sided (as in both the journey and the destination are great but both in a different way) beauty of debugging, probably even this explanation is not the right way of saying it and I currently have no better way to put it (English not my first language)

I really did not want to offend you, you have no reason to believe me or accept my apology and I get that

I would remove the comment but that would just be covering it up, if you want to remove that comment then fine, otherwise is fine with me too, I did mess up, sorry

**Closed** 2019-07-14 23:52 UTC
