### ISSUE TITLE
After watching a show, Trakt is not marking episode as watched

### ISSUE THREAD

**Issue by jpcaba** [123Venom/plugin.video.venom#182] opened 2022-04-06 19:33 UTC
Operating System: Android 
Device: Google chromecast with google TV
Version of Kodi: 19.13
Version of Venom add-on: Latest
Country: USA
Debrid services in use: Real-Debrid

After watching a show, sometimes the show is not marked as watched in trakt.  I have noticed this if I have a show on pause for a while.

**Comment by TapMeDead** [comment] 2022-04-06 19:42
@jpcaba You must watch more than 85% of a show for Venom to mark it watched. Some shows have very long credits in the end, and you will have to push closer to the end for it to get marked watched.

**Comment by jpcaba** [comment] 2022-04-06 20:27
@TapMeDead, I know how an episode is marked as watched.  I know the 85% rule.  This issue started happening with the latest update released this week.

**Comment by 123Venom** [comment] 2022-04-06 20:49
I've not seen this happen here yet.  Was there a particular show this happened on?  I know we've had a few reports of some shows not marking and when we traced it turned out Trakt had incorrect ID's.  One show in particular was `The Witchfinder`.  I had reported it to Trakt and supposedly the show was fixed but I've not confirmed it yet.  Another show was `Badger`

**Comment by jpcaba** [comment] 2022-04-06 21:07
It happened with Power Book IV: Force.  It happened with Castle.  It happened with The Rookie.
However, it works if I manually mark it as watched in trakt.  I wonder if it's the waiting on pause for a long time and then when I finish the episode it doesn't try or I cannot tell if it is trying (no notification).  However, it does reset the scrobble.

The same shows I mentioned above also will automatically mark it watched if I do not leave it paused for so long.

**Comment by 123Venom** [comment] 2022-04-06 21:16
ya I just spoke with another user and he said he's noticed the scrobble seems to not get reset.  I seldom ever pause so perhaps that's why I do not see it.  So your just pausing it for an extended period of time and coming back to it and unpausing then it seems to happen?  Any common position you are pausing it?  I'll try to reproduce it.  The latest version I did some changes because the saved scrobble points did not match the true point you saved it...long story but has to do with Kodi using seek in seconds while Trakt stores in percent watched.  It really should not have had an effect on the scrobble being reset but I've seen all sort of weird shit break other stuff for no explained reason.

**Comment by 123Venom** [comment] 2022-04-06 21:18
and btw...if the scrobble is not being reset try using the `Trakt Manager` and use `Scrobble Reset` then the watched indicator should show.  Resume points take priority so they'll show over a watched indicator.

**Comment by jpcaba** [comment] 2022-04-06 21:20
It is resetting the scrobble but not marking as watched.

I will start a show and then I'll get a call and I will pause the show.  Sometimes it would be on pause for up to 1 hour.  Then resume and finish the show, but no marked as watched.  Just an empty square box.

**Comment by 123Venom** [comment] 2022-04-06 21:21
Interesting..User I spoke with said for him it was the scrobble reset not happening

**Comment by jpcaba** [comment] 2022-04-06 21:22
I have seen that but VERY rarely.  I just reset it manually.  I have not seen it recently though.

**Comment by 123Venom** [comment] 2022-04-06 21:25
ya he said it's rare.  Kodi has a bad habit of occasionally not issue player callbacks that we use to monitor what you pressed, or video ended etc. I'll do the best I can to reproduce it.

**Comment by jpcaba** [comment] 2022-04-06 21:27
Nice one Kodi.  Now I have only experienced this with TV shows.  Not movies, if that helps?

**Comment by 123Venom** [comment] 2022-04-06 21:29
> Nice one Kodi. Now I have only experienced this with TV shows. Not movies, if that helps?

I'll be sure to test just shows but honestly the same methods are performed and should not make a difference to it being marked as watched.

**Comment by jpcaba** [comment] 2022-04-06 21:31
Thank you!

**Comment by jpcaba** [comment] 2022-04-07 03:14
So I tried again with Young Sheldon. This time I fast forwarded to the end and stopped it to see if it would mark as watched. It did not. Here is the log. 

![image](https://user-images.githubusercontent.com/99694885/162112974-a900c54c-a425-4c94-9329-916595766b8e.png)

**Comment by jpcaba** [comment] 2022-04-07 03:25
Plot twist. I think it is marking as watched but not refreshing it as watched in the container refresh. It shows an empty box. When I back out to progress, the episode is there and empty box. When I back out to main menu and back to progress, the episode is gone. When I search for the episode, it now has the check mark as watched. I will try again yo confirm this tomorrow and update you then.

**Comment by TapMeDead** [comment] 2022-04-07 03:28
@jpcaba You can try enable "Force container refresh" in the "Playback" section of Venom settings. This will refresh your page automatically, but it will take an extra second or two every time you come out of the video player.

**Comment by jpcaba** [comment] 2022-04-07 10:32
That is already turned on. It is still happening with that on.

**Comment by jpcaba** [comment] 2022-04-07 11:50
So strange. It did not mark it watched when the container was refreshed. When I moved back to progress, it removed it from progress. I searched for the show and the episode was not marked as watched. I had to manually mark it as watched. Container refresh is turned on.

**Comment by 123Venom** [comment] 2022-04-07 16:41
@jpcaba something is a bit confusing here.

Here you say when you searched for it the episode is marked as watched.
https://github.com/123Venom/plugin.video.venom/issues/182#issuecomment-1091039494

Your response directly above this reply I assume is same title/episode but now you said it's not marked as watched?

It's almost sounding like a container refresh issue.  Some skins do their own and the setting is not needed to be used.  Try turning it off.  What skin?  I've run 3 tests and not been able to duplicate it as of yet.

**Comment by 123Venom** [comment] 2022-04-07 17:08
I just used your **Young Sheldon S05E17** test case and now I was able to duplicate it.  I had to search for the title but once it appeared as if not marked my hunch was a container refresh issue, and I'm set to on/enabled in settings, I backed up to season level and went back in to S05 and it now that episode was marked as watched.  Unfortunately the container refresh is just a command we issue as `xbmc.executebuiltin('Container.Refresh')` and you can see it take place by a quick flash of a busy dialog/spinner.  I did not see it and if it doesn't respond to the command there's not much I can do about it.

You're using the same skin as I so we can be thankful we're comparing apples to apples if the skin is having an effect on this.

As for this not happening until the last update, that's a mystery.  The change I made had nothing to do with this.  I changed how the resume point scrobble position is calculated from the Trakt percent watched they use for when playback STARTS...stopping and marking as watched is different code, different callback, in different location and should not be impacting this.  I'm at a loss atm on this and need to ponder it more.

**Comment by 123Venom** [comment] 2022-04-07 17:12
lol...I unmarked the episode and repeated the EXACT same procedure as I did in last test that duplicated your issue.  This time the container.refreshed occurred and the indicator was shown.  Go figure.  The same code just did two different things.

**Comment by jpcaba** [comment] 2022-04-07 17:14
So it did that behavior for me too at Young Sheldon.  Today I watched Star Trek Picard, the last episode and it did not do the same thing as Young Sheldon.  It removed it from Trakt Progress but when I searched for that epsiode, it displayed as not marked as watched.  I had to manually mark it as watched in the context menu.

Could our differences be that I am on 19.3 of Kodi?

**Comment by 123Venom** [comment] 2022-04-07 17:21
> Could our differences be that I am on 19.3 of Kodi?
I doubt it.

I had a look at the log of the failed container.refresh vs. when it worked and spotted one difference.

<img width="1611" alt="refresh" src="https://user-images.githubusercontent.com/46383815/162260079-71535ac2-7e76-4298-ac95-bc937e5183a7.PNG">

A background service sync for one item occurred 13secs after the Kodi callback was issued.  I would not think that would muck with the refresh being 13secs later and the refresh should be immediate.

That's odd the item is removed from your Progress yet not marked as watched...absolutely never seen that happen.  The only way items advance in the Progress is the Trakt response changes the watched items.  

Is this from a widget or are you inside Venom?

Silvo does not use indicators on widgets, which I think is retarded. Just pointing that out.

**Comment by jpcaba** [comment] 2022-04-07 17:24
I do not use widgets.  This is inside Venom.  My logs are missing lines 1648 and 1649.  

I too found that strange.

**Comment by 123Venom** [comment] 2022-04-07 17:30
I just tested Star Trek: Picard S02E06.  Two times in a row the container.refresh failed to occur but backing out and going back in and the watched indicator was there.  Your container.refresh issue I can duplicate an inconsistent behavior with...your issue with items being removed from Progress yet not marked as watched I can not.  In both failures that time I seeked to about 2mins remaining...sat for about 5secs and then stopped it.  When you do seek try to let it play out for about 5secs so the new position is registered.  I've had users seek and then immediately stop it and that does not give the xbmc.player time to record the new position.  Just mentioning it.

**Comment by jpcaba** [comment] 2022-04-07 18:03
I am thinking the remove from progress and not marked as watched is a fluke. 

So the issue is probably the container.refresh?

**Comment by 123Venom** [comment] 2022-04-07 18:06
> I am thinking the remove from progress and not marked as watched is a fluke.

That's what I'm thinking because I can't duplicate that one.  I even had 2 other users test that for me and still can't reproduce it.


> So the issue is probably the container.refresh?

That's what it's looking like here.  I've ever run 2 more tests on Picard and 2 out of 4 it failed to refresh.  I'm at a loss what causes it.

**Comment by jpcaba** [comment] 2022-04-07 18:12
Can you try with Below Deck Down Under?  That one seems to not even mark as watched at all.  As I backed into progress after finishing the episode it was still there in progress.  I even left progress and re-loaded it and the episode was still there.  I had to manually mark that one.

**Comment by 123Venom** [comment] 2022-04-07 18:12
ok..reviewing the code I was wrong.  I do not issue a container.refresh when playback was stopped and the watched % is greater than 85%.  In my experience skins do their own refresh and it's apparent because if I'm not issuing that command yet sometimes it happens then the skin HAS to be doing it yet is inconsistent with it occurring.  If you stop a video at say 50% I do then issue the container.refresh because skins generally do not do it at that condition.

**Comment by 123Venom** [comment] 2022-04-07 18:14
> Can you try with Below Deck Down Under? That one seems to not even mark as watched at all. As I backed into progress after finishing the episode it was still there in progress. I even left progress and re-loaded it and the episode was still there. I had to manually mark that one.

I'll test that one.  We've had a few shows not mark as watched and when traced it was do to bad ID's from Trakt.  If it's not marking as watched and still remains in your progress that sounds oddly just what was happening on those 2 shows I mentioned.

**Comment by 123Venom** [comment] 2022-04-07 18:16
usually the first sign of an ID problem is attempting to manually mark as watched and it fails.  That show you just gave me I marked S01E01 and it worked fine so we can rule out an ID issue

**Comment by jpcaba** [comment] 2022-04-07 18:17
Understood.  Particularly the last episode of that series, which I experienced pretty recently today.  I had to manually mark it as watched and that did mark it as watched.

**Comment by 123Venom** [comment] 2022-04-07 18:18
I seeked to 2mins remaining..sat for 5secs and stopped it.  It was marked as watched and I noted the container refresh took place.  Seemed fine here.

**Comment by 123Venom** [comment] 2022-04-07 18:22
Weird.  That time no refresh occurred..backed out and went back in and ep6 still not marked.  Then all of a sudden a refresh occured while sitting there but no indicator shown...backed out and back in again and now it's there.  Massive delay in that container refresh happening.

**Comment by 123Venom** [comment] 2022-04-07 18:27
Unmarked it and retested.  This time I sat on the item after stopping playback.  Literally 10secs later I witnessed the refresh occur but no watched indicator.  Backing out and going back in ep6 now had the indicator.  I'm afraid whatever is taking place with this refresh and lack of indicator being instantly shown I'm not going to be able to fix.

**Comment by 123Venom** [comment] 2022-04-07 18:32
I also noticed if I let it play right to the end, even after the massive manual seek, the refresh is instant and the indicator is consistently showing up right after the refresh.  Seems stopping it beyond 85% watched has an inconsistent behavior.

**Comment by 123Venom** [comment] 2022-04-07 18:42
I uploaded a modified player module here...

https://github.com/123Venom/zips/tree/dev

Test it for me.  Drop it in here....
`\addons\plugin.video.venom\resources\lib\modules`

What I did was to force the container.refresh and not rely on the skin to do it.  Problem I found before in doing this is if the skin and addon both do it I've seen it refresh to end up with doubled up listitems..ohh you'll notice it if it happens...but...since that time I stopped using a Kodi feature called `cacheToDisc` and that very well may have contributed to the doubled up listitems when both skin and addon do a refresh.  Test that out thoroughly and lets see if that is any better.

**Comment by jpcaba** [comment] 2022-04-07 19:08
So I put the file in. The first time it did a container refresh but was not marked. I thought it was done but it did a second refresh but I hit back thinking it was done on the first refresh. But it did mark it watched. I think tried a second time and it did what you said, doubled the listitems. 

![image](https://user-images.githubusercontent.com/99694885/162278410-1517182f-8a36-4fa5-a85a-e067b5160dec.png)

**Comment by 123Venom** [comment] 2022-04-07 19:14
yep..that's the issue with both skin and addon trying to do a container refresh.  I'm also testing it and haven't seen it happen yet myself on that modded player module.  Least now I know that `cacheToDisc` feature no longer in use doesn't have an effect and we can't both be doing a refresh.  I'm afraid I have no solution for this.

tbh I seldom ever stop videos and that seems to be where the inconsistency comes from, least here that's what I see and that's what I'm saying I can't cure it.

**Comment by TapMeDead** [comment] 2022-04-07 19:17
Might I suggest, try setting up Play Next. It works wonders for binge watching, plus I've never seen this issue while using it.

**Comment by jpcaba** [comment] 2022-04-07 19:22
@123Venom Thanks for your help with this.  I just find it strange that all of a sudden this is happening with no updates to the app itself.  I even checked if there was an update to the skin itself but nothing.

I am going to try to let it stop on its own and see how that works out.

@TapMeDead I tried that in the past but I was not a fan of it.  I may give it another go since it was with an older version of Venom.

**Comment by 123Venom** [comment] 2022-04-07 19:24
@jpcaba my wife watches alot of shows and woman hate that source select shit.  She uses the `Play Next` feature primarily and works well for her and her AutoPlay desire.  I'd give it another go...lots changed in that.

**Comment by jpcaba** [comment] 2022-04-07 19:28
@123Venom Awesome.  My wife is the same.  I might give it a go.

Also, I update back to 6.5.5 and the stop is now marking it as watched and the end playback on its own is also doing it.  Not sure why.  I will update my other devices and keep testing.  But again thank you for your help... Truly appreciate it.

**Comment by jpcaba** [comment] 2022-04-07 19:35
Can you tell me more about PlayNext?  Does it automatically play the next episode once done with the one you are watching?

Do I only need to enable the PlayNext setting or is there something else I need?

**Comment by TapMeDead** [comment] 2022-04-07 19:36
@jpcaba Since first edition of PlayNext, some features have been added, and some adjustment features in settings to make it behave as you want. Those settings are under "TV Shows" in Venom settings.

**Comment by jpcaba** [comment] 2022-04-07 19:38
@TapMeDead thank you!  I remember having to use an addon and I think that's why I didn't like it.  I was trying to recreate the Netflix style of going to the next one.  But it didn't work well for me, especially when I had broken links.  I'm talking about Venom v4.

**Comment by jpcaba** [comment] 2022-04-07 19:58
Cool. I will check it. Thank you.

**Comment by 123Venom** [comment] 2022-04-07 19:59
There's a help file below the `Play Next` setting that's a good read.

**Comment by jpcaba** [comment] 2022-04-07 20:54
I like the playNext!plaintext!! Thanks guys.

**Comment by 123Venom** [comment] 2022-04-07 23:05
There's a few things to keep in mind when using `Play Next`.  If you launch it from your Trakt `Progress` it's going to attempt a playlist based on what's visibly on your screen.  You want to make sure `Direct progress Scraping` is turned off, if it already was then no issue to worry about.  Then when when you hit enter on a Progress item it will load the remaining episodes for that season.  Then what episodes are visible becomes the playlist when you hit enter.  As long as you just follow a principal of what listItems are visibly on the screen is what your playlist will be based on when playback is launched for what's going to play in a continual fashion.  I'm working on making the listItems work with a flatten ability to not just load the remaining episodes for that season but ALL remaining episodes for the series.  You asked about that in the other issue...

https://github.com/123Venom/plugin.video.venom/issues/184

**Comment by jpcaba** [comment] 2022-04-07 23:53
Awesome. I understand. For me direct progress scraping is off. 

Thank you so much. This is exciting new.

**Comment by jpcaba** [comment] 2022-04-08 03:28
Question: I am curious to know if this happens to you. Today I watched castle s05e08 and playnext went to s05e09. We finished both and I stopped it from going to e10. When it brought me back to the episode list, only e09 was marked as watched. I had to manually mark e08 as watched. Before marking as watched i went back to progress and e08 was next on the list. I also went completely out of progress and reloaded the progress and e08 was next on the list. The same behavior with Schitts Creek s06e04. I stopped s06e05 in the middle. It came back to the list and e04 was not marked as watch and e05 was scrobbled. Does this happen to any of you when using playnext?

**Comment by TapMeDead** [comment] 2022-04-08 03:32
@jpcaba I use PlayNext all day every day, and what you just described has only ever happened if I skip to next, before the playback is 85% into the show, then it didn't register as watched.

**Comment by jpcaba** [comment] 2022-04-08 03:37
Literally there was 10 seconds left in castle before I hit the play now button to go to e09. 

For Schitts creek there was 40 seconds left in the episode before I hit play now on the pop-up. 

Also, I have set the pop-up to come up 60 seconds before the episode ends, that's like 99% of the episode is watched. Lol. I don't know why it's doing it to me. And it did it on 2 devices. Both Google chromecast with google tv.

**Comment by TapMeDead** [comment] 2022-04-08 03:40
@jpcaba Yeah I understand, so next is to figure out why your "watched" requests aren't getting registered and sent back to you fast enough. May I ask how long its been since you rebooted router and such?
I have this idea in my head that since this only happens to you, more or less, something in your system is blocking, or delaying things going back/forth to register your 'watched' indicators

**Comment by jpcaba** [comment] 2022-04-08 03:53
Interesting. I haven't rebooted the device itself in about a month. I have google wifi and I rebooted that about a month ago. I get a gigabit of speed up and down. I will reboot my device and wifi and give that a shot tomorrow.

**Comment by jpcaba** [comment] 2022-04-08 03:58
I just did it on my phone and it works well there. Very strange. I will reboot the network and all devices and test it tomorrow. Thanks.

**Comment by TapMeDead** [comment] 2022-04-08 03:59
@jpcaba Good idea, I will try look into chromecasts, maybe this is a common issue, or at least 'known of' in the streaming communities :)
Let me add, I work closely with 123Venom, I call myself his beta tester heh, can take no credit whatsoever, but I've helped him find bugs and with testing new additions a lot. I don't know much about the code itself, but I watch tv on avg. 12h every day, or more, never less heh. I know Venom, at least the settings I use for efficiency in binge watching hehe

**Comment by jpcaba** [comment] 2022-04-08 04:02
Awesome. That's cool. Let me know if you need help testing on a chromecast device. I have 3. Lol. I'm a software developer myself but on .NET side. I can understand what the code is doing in python but I don't know the syntax of it on how to use it efficiently.

**Comment by TapMeDead** [comment] 2022-04-08 04:04
@jpcaba Let's see if we can't get to the bottom of this tomorrow, I will keep an eye on this post :)

**Comment by jpcaba** [comment] 2022-04-08 04:12
Good call. I rebooted the device and now it is working. So strange.

**Comment by TapMeDead** [comment] 2022-04-08 04:48
@jpcaba Good good, give a msg here tomorrow if things work, so 123Venom can close the issue.

**Comment by 123Venom** [comment] 2022-04-08 04:55
>When it brought me back to the episode list, only e09 was marked as watched. I had to manually mark e08 as watched. Before marking as watched i went back to progress and e08 was next on the list

Something there once again is not adding up.  I can manually mark a season `e09` as watched and Trakt is going to return `e10` as my next item to watch.  You're saying before you even marked a thing that `Trakt-Progress` was showing `e08` as you next item when you just said only `e09` was shown marked as watched?  Absolutely no freakin way!!!  I have never had a report of that happening nor EVER seen that...showing a lesser episode to watch as next when it marked `s09'?.  The only confirmed issue I've seen is what kodi/skin is inconsistently doing on stopping a video before it's end point when it's clearly a WATCHED condition.  That I confirmed to be an issue and one I said I can not solve the inconsistency with a refresh occurring.  I'm going to leave this in the hands of @TapMeDead if he wants to attempt to resolve this but I can no longer invest hours into this as something just does no add up.  I'm sorry if that seems harsh it's just things are not making sense to me nor can I replicate so I'm at the end of my rope and extremely frustrated. @TapMeDead is a die hard daily show watcher yet he has not seen this issue either.  You're in good hands with him...he's taking over issues for me due to available time.

I'd honestly STRONGLY suggest at this point to test another addon that might suits you better as I just do not believe Venom is going to be it for you.  I really do wish I could help you more but this is getting redundant and not reproducible.

**Comment by jpcaba** [comment] 2022-04-08 10:47
Seeing this is sad to read. I wouldn't make shit up. I know how trakt works
and i too found it interesting that it was behaving that way. I never seen
it do that. Definitely shouldn't loose your cool and let it show to the
people who use your software. I would never react like that and show it to
a customer that uses my software.

Anyways, thank you for your time and help. As I said before, it really is
appreciated.

**Comment by jpcaba** [comment] 2022-04-08 18:23
@TapMeDead still an issue.  Very annoying.  Today I watched the witcher s01e04.  PlayNext took me to s01e05.  I stopped s01e05 after 2 minutes and the container came back and didnt look marked as watched but it did.

Then I did star trek voyager s02e09 and it did not mark it watched and it went to s02e10 with playnext.

**Comment by jpcaba** [comment] 2022-04-08 18:23
I am wondering if its old shows.

**Comment by TapMeDead** [comment] 2022-04-08 18:28
This is very odd, since its not happening to me or the Dev even when we try to make it happen.
I do remember one of the "witcher" shows having resume point and watched indicator problems because of inconsistent data across the platforms used for this action (Trakt and TMDB). 
Did you reboot all devices, plus router and other wifi related devices you may have?

**Comment by TapMeDead** [comment] 2022-04-08 18:31
I just watched 9 episodes of "The Originals" all 9 were set watched just fine.

**Comment by jpcaba** [comment] 2022-04-08 18:41
> This is very odd, since its not happening to me or the Dev even when we try to make it happen. I do remember one of the "witcher" shows having resume point and watched indicator problems because of inconsistent data across the platforms used for this action (Trakt and TMDB). Did you reboot all devices, plus router and other wifi related devices you may have? You might also try clearing cache in Venom, I usually clear all, but should be enough to clear "Cache" and "Metadata Cache", to avoid losing your searches and such.

I did reboot everything. I wonder if the chromecast are too slow but never had this issue in the past. I wonder if I can go to an older version of venom and try this again.

**Comment by TapMeDead** [comment] 2022-04-08 18:42
Just tried with Voyager, same ep you mentioned, I put it at 2 min before end, waited for PlayNext at 1 min, hit Next, went to episode 10 as intended, I then stopped playback, came back to inside season and the check is there.

![Screenshot_1](https://user-images.githubusercontent.com/99356645/162502054-ca56bf2a-97fe-478f-b854-5b84fc9250e8.png)

**Comment by TapMeDead** [comment] 2022-04-08 18:43
Try clearing your Venom caches, I would just do "All" but try what I said above first.

**Comment by jpcaba** [comment] 2022-04-08 19:38
It has to be the chromecast then. But again this is the first time happening with the chromecast. 

I have cleared all cache in venom and still happens.

**Comment by 123Venom** [comment] 2022-04-08 19:40
@jpcaba how about this.  When an item appears to not get marked as watched head over to the trakt web site and check it there...site show you've watched it?

I'd even try a "Force Trakt Sync to local database"

**Comment by TapMeDead** [comment] 2022-04-08 19:40
Maybe you could try installing, say, for example The Oath, then see if it works there.
If it does, maybe consider re-installing Venom or all og Kodi + Venom.
Something is weird at your end, sad to say.

**Comment by 123Venom** [comment] 2022-04-08 20:06
@jpcaba I uplaoded a slight mod change to the trakt module here....

https://github.com/123Venom/zips/tree/dev

drop it in here....
`\addons\plugin.video.venom\resources\lib\modules`

All I added was a logging entry on line 938 in pic so we can see the trakt api response.
<img width="1071" alt="trakt_mark as watched" src="https://user-images.githubusercontent.com/46383815/162518108-5cdc1e28-2a1d-4816-bf89-0ba0900fe34d.PNG">

Make sure you do that same procedure I explained after you drop the file in...exit Venom to another addon and back again so the code change is re-read.  When you get a failed to mark toss the log up and lets see what the api returns.

I owe you an apology for yesterday.  I was burnt out and extremely frustrated on not being able to replicate this problem and the more testing and time I spent on it seemed your issue just kept getting worse.

**Comment by jpcaba** [comment] 2022-04-08 20:17
I appreciate the help. I will give this a go shortly. Thank you.

**Comment by jpcaba** [comment] 2022-04-09 02:34
So I added the file. I sat and watched s05e10 of castle. Finished the episode and playnext took me to s05e11. I didn't finish e11. I stopped it at 18 minutes. Came back to the Playlist and e10 was not marked watched and e11 was scrobbled. 

Below are the images of the log:

**Comment by jpcaba** [comment] 2022-04-09 02:34
![image](https://user-images.githubusercontent.com/99694885/162553367-f8e1f11a-930b-459b-97d6-db8b93b9d1a7.png)

**Comment by jpcaba** [comment] 2022-04-09 02:36
![20220408_222952](https://user-images.githubusercontent.com/99694885/162553404-696deda3-39fe-490e-b16f-5bb3e2239a49.jpg)

**Comment by jpcaba** [comment] 2022-04-09 02:36
![20220408_223001](https://user-images.githubusercontent.com/99694885/162553410-eb9b9c3e-a382-4eab-a52b-f8a9e1e074c5.jpg)

**Comment by TapMeDead** [comment] 2022-04-09 02:40
123Venom actually just fixed this, I am testing a new player.py file that cures the scrobble happening like this :)
I can't post files though, he has to do that, will call him up if I can.

**Comment by jpcaba** [comment] 2022-04-09 02:47
Awesome. Thank you.

**Comment by 123Venom** [comment] 2022-04-09 02:49
https://github.com/123Venom/zips/tree/dev

@jpcaba you can test that.  It fixes an issue discovered where the previous scrobble would not get reset...sort of a hack solve I'm not happy about but few of us discovered an issue with Kodi playback callbacks being unreliable. Kodi itself have a decent set of bugs to deal with.

That last pic you posted has Trakt timeout error.  Then notice the None type error immediately after when trying to mark as watched...BINGO....That's the source of your watched problem because Venom did not get an api response from Trakt and timed out.  Could a had that log data yesterday..lol

**Comment by jpcaba** [comment] 2022-04-09 03:00
Shit sorry guys. I will try this out and follow up.

**Comment by jpcaba** [comment] 2022-04-09 03:01
Is it the player.py?

**Comment by TapMeDead** [comment] 2022-04-09 03:01
@jpcaba Can I ask how old your Chromecasts are?
Yes player.py

**Comment by jpcaba** [comment] 2022-04-09 03:04
> @jpcaba Can I ask how old your Chromecasts are? Yes player.py

I bought one 6 months ago. The other two are 1 month old and 3 weeks old. All three have the same backup from my original chromecast.

**Comment by 123Venom** [comment] 2022-04-09 03:05
@jpcaba I upladed a revised trakt module for you to test.  I bumped the allowed timeout to 20.  For some reason 10 times out for you, shouldn't.  The other concern I have with that is I use a 10sec timout pretty much throughout.  My fanarttv and tmdb modules also have 10sec timeout values.  You could potentially have more issue than just this one.

**Comment by TapMeDead** [comment] 2022-04-09 03:06
Okay, just talking about your API requests timing out, they are set to 10 seconds, which is more than enough for most people these days. Something is slowing you down :)

**Comment by jpcaba** [comment] 2022-04-09 03:08
Interesting. I've noticed that sometimes the episode has an image from the episode and sometimes it has just the season cover. Could that be related to that time you are referring to?

**Comment by 123Venom** [comment] 2022-04-09 03:12
@jpcaba I posted the wrong trakt module....download again.  Sorry I'm literally flying all over the place chattin with 3 and it's not working out well for me..lol

**Comment by TapMeDead** [comment] 2022-04-09 03:13
@jpcaba you wouldn't happen to have a few teens in the house sucking up all your bandwidth? heh, something like that anyway :)

**Comment by jpcaba** [comment] 2022-04-09 03:14
> @jpcaba I posted the wrong trakt module....download again. Sorry I'm literally flying all over the place chattin with 3 and it's not working out well for me..lol

No problem. Will do it now.

**Comment by 123Venom** [comment] 2022-04-09 03:14
> Interesting. I've noticed that sometimes the episode has an image from the episode and sometimes it has just the season cover. Could that be related to that time you are referring to?

log would tell us..just post the whole thing and not snips!!

**Comment by jpcaba** [comment] 2022-04-09 03:15
> @jpcaba you wouldn't happen to have a few teens in the house sucking up all your bandwidth? heh, something like that anyway :)

I do but I have a gigabit connection and Google wifi handles the load balancing really well between the 3 mesh networks.

**Comment by 123Venom** [comment] 2022-04-09 03:15
after seeing that timeout I'm concerned you got more of that going on

**Comment by jpcaba** [comment] 2022-04-09 03:15
> > Interesting. I've noticed that sometimes the episode has an image from the episode and sometimes it has just the season cover. Could that be related to that time you are referring to?
> 
> log would tell us..just post the whole thing and not snips!!

Where is the log so I can grab the whole file and upload it?

**Comment by TapMeDead** [comment] 2022-04-09 03:28
Not sure about where it is on Android, but on windows its at c/users/[username]/Appdata/roaming/Kodi filename venom.txt.
Being told its in /temp on Android now. You might have to search for it to find the path

**Comment by 123Venom** [comment] 2022-04-09 03:29
What's wrong with this?

<img width="915" alt="12c" src="https://user-images.githubusercontent.com/46383815/162554691-29234a7c-5311-40b5-98ee-2f811751e0f7.PNG">

**Comment by jpcaba** [comment] 2022-04-09 04:06
I found it. There's a temp folder inside the .kodi folder where the log is written. I have uploaded the new log to pastebin. Here is the url: https://paste.kodi.tv/oqojigaduy

It is now working correctly for me. There was some errors in the log file with getSources_silent() had to do with importing from fenomscrapers. The other was getEpisodeSource() keyError -> _bootlocale. 

All in all, this is now working for me. It's marking them watched with no issues. Thank you guys.

**Comment by 123Venom** [comment] 2022-04-09 05:28
The `getSources_silent()` import issue was already known and resolved. I removed an age old method from FenomScrapers that is not used anymore and neglected I did still have an old import method in Venom looking for it, yet was not used.  I uploaded a new `sources.py` module to dev branch if you want to drop that in to rid the error.  It will be in official release when I can get enough free time to finish it.

The ` _bootlocale` error is coming from a call to a `getEpisodeSources()` method and this is a call to scrape for episodes source links.  This error comes from the cloudscraper/cfscrape module.  This module is not written by us and not much we can do about it.  It's basically a 3rd party module we use to get around cloudflare.  The `fenomscrapers.log` should point to what scraper module made the call that failed.  You could find that and maybe disable the offending scraper but sometimes it's also a momentary glitch you just have to watch for to know if it repeats THEN disable it.  It's not a huge deal...the scraper will just fail to return sources and that's it.  We've been loosing scrapers alot lately due to cloudflare or domains closing up.

I've bumped timeout values across the board for all meta providers to 20secs, against my better wishes.  That change will be in official and may fix your other poster issues...might not..no idea.  Your log was not even a full log, it spanned 4mins so I couldn't very much of anything else from the lack of data...lol.  Once I do push official I'm going to hide for a month...lol.

**Comment by jpcaba** [comment] 2022-04-09 14:29
Lol. A well deserved month indeed.  Lol. Thank you.

**Closed** 2022-04-10 16:12 UTC
